doc/building.md
for_devs_on_macos/README.md
for_devs_on_macos/installers/all.sh
for_devs_on_macos/installers/boost.sh
for_devs_on_macos/installers/common.sh
for_devs_on_macos/installers/cppcheck.sh
for_devs_on_macos/installers/llvm.sh
for_devs_on_macos/installers/openssl.sh

This doc is a bit spartan, but I think it is concise and sufficient. It relies on a minimal reader's googling ability. I also assume that the reader will solve many implicit problems just by going with the flow (e.g. setting up brew will require installing xcode tools). I preferred to not describe well-known things here.  
It would've been nicer to list exact brew packages needed, but to find that list I would need to remove everything in brew locally, and go through trial-and-error from scratch.

MacOS dev doc

---

src/consensus/pbft_chain.cpp
src/consensus/pbft_chain.hpp
src/consensus/pbft_manager.cpp
src/dag/dag.cpp
src/dag/dag_block_manager.cpp
src/node/executor.cpp
src/node/executor.hpp
src/node/full_node.cpp
tests/full_node_test.cpp
tests/pbft_chain_test.cpp
tests/pbft_manager_test.cpp

Fixed and optimized the executor

---

src/chain/final_chain.cpp
src/network/rpc/Net.cpp
tests/final_chain_test.cpp

network id needs to be an integer, and we should default to expectation of chain id
_Provide any information reviewers might need to have context on your changes_
_Describe anything you want to call out to the reviewers e.g. areas to focus on, decisions you made, specific feedback you are looking for, etc._
_Describe what you did to test the changes you made. Include evidence such as screenshots or terminal commands and output._
_Decide whether this is a major, minor, or patch version change. Major is for backwards incompatible changes (This is only relevant once the service is live and in production and the major version is at least 1. While the major version is 0, it is ok to have backwards incompatible changes in a minor version.). Minor is for additional …

RPC changes for truffle and additional tooling support

---

src/CMakeLists.txt

This fixes the heap corruption issues in some tests

Static initialization/linking fix

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp
tests/network_test.cpp

Improve PBFT Network Sync

---

conanfile.py
doc/building.md

Some bugs with clang tools version.
Changed downloading llvm on macOS in conanfile.py
Updated docs for macOS

Updated build docs for macOS; Fixed conanfile.py

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp
tests/network_test.cpp

Improve network PBFT syncing

---

config/networks/testnet.json
src/transaction_manager/transaction_manager.cpp

_Provide any information reviewers might need to have context on your changes_
_Describe anything you want to call out to the reviewers e.g. areas to focus on, decisions you made, specific feedback you are looking for, etc._
_Describe what you did to test the changes you made. Include evidence such as screenshots or terminal commands and output._
_Decide whether this is a major, minor, or patch version change. Major is for backwards incompatible changes (This is only relevant once the service is live and in production and the major version is at least 1. While the major version is 0, it is ok to have backwards incompatible changes in a minor version.). Minor is for additional features. Patch is for bug fixes._
_Describe the changes in this version. This is …

Trx deduplication

---

Jenkinsfile

Change jenkins to use helm3

---

src/consensus/pbft_manager.cpp

Fix DAG blocks syncing issue

---

CMakeLists.txt
Dockerfile
tests/crypto_test.cpp

Any C++ code has many places with memory leaks and undefined behavior. Therefore, it is necessary at the moment to identify these places and fix them, and in the future to fix them before getting to develop.
Added google address and undefined sanitizers to build (enabling by cmake option).

Added google address and undefined sanitizers option to build

---

Dockerfile
conanfile.py

To cache libraries install step on Docker we need to add debug flag to it.
Also some fixes for clang tools location.

Added debug to conan install

---

src/consensus/pbft_manager.cpp

_Provide any information reviewers might need to have context on your changes_
_Describe anything you want to call out to the reviewers e.g. areas to focus on, decisions you made, specific feedback you are looking for, etc._
_Describe what you did to test the changes you made. Include evidence such as screenshots or terminal commands and output._
_Decide whether this is a major, minor, or patch version change. Major is for backwards incompatible changes (This is only relevant once the service is live and in production and the major version is at least 1. While the major version is 0, it is ok to have backwards incompatible changes in a minor version.). Minor is for additional features. Patch is for bug fixes._
_Describe the changes in this version. This is …

fix pbft second finishing state reached late logging

---

tests/network_test.cpp
tests/pbft_rpc_test.cpp

Fix unit tests timing issue

---

config/networks/devnet.json
config/networks/testnet.json

Devnet and Testnet config changes to increase committee size to 1000

---

Dockerfile
src/common/static_init.hpp

Trying to catch coredumps in docker

Playing with core dumps in docker

---

.github/workflows/issue-link.yml

automatically link PR to an existing issue through "#resolve" comment. For this to work, branch name must consis of issue-<NUM> string, e.g. feature/issue-724/my-custom-branch-name

chore(git-flow): added automatic issue linking action

---

src/consensus/pbft_manager.cpp
src/consensus/vote.cpp
src/consensus/vote.hpp
tests/vote_test.cpp

Remove last PBFT block hash checking in vote validation, need to remove last PBFT block hash in VRF message later

Remove last PBFT block hash checking in vote validation

---

src/dag/dag_block_manager.cpp
src/dag/dag_block_manager.hpp
src/network/taraxa_capability.cpp
src/node/executor.cpp
src/storage/db_storage.cpp
src/storage/db_storage.hpp
tests/full_node_test.cpp

Fix DPOS max proposal period consistent

Fix DPOS max proposal period consistent

---

src/network/taraxa_capability.cpp

style: fix clang-format err

---

CMakeLists.txt
Dockerfile
src/CMakeLists.txt
submodules/CMakeLists.txt

This PR consist of 2 things:
- most of the changes are improving building optimization
- I have also add linking with gperftools for heapanalysis

cmake: improve building optimization & flags for heap analysis

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/network/taraxa_capability.cpp

feature: Refactor PBFT sync initiation and logging

---

src/storage/db_storage.cpp

Fix coredump on rebuild_db flag

Fix core dump when creating snapshot with rebuild_db flag

---

src/consensus/vote.cpp
src/node/full_node.cpp
src/node/full_node.hpp
src/storage/db_storage.cpp

https://github.com/Taraxa-project/taraxa-node/issues/773

Full node check DAG genesis hash

---

src/consensus/vote.cpp
src/consensus/vote.hpp
src/dag/dag_block.cpp

Small changes to significantly improve processing of votes

perf(vote): speed up vote processing

---

doc/git_practices.md

See description in related github issue

docs(git-flow): added proposed conventions for git-flow

---

.circleci/config.yml

Circleci prtest - Test trigger circleci build on PR creation 

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp

For status packets, need to check if receive the initial one
https://github.com/Taraxa-project/taraxa-node/issues/787

Bugfix/issue 787/Check initial status packet

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp

Reverts Taraxa-project/taraxa-node#788
Is not passing unit tests. :-)

Revert "Bugfix/issue 787/Check initial status packet"

---

.circleci/config.yml
.github/workflows/circleci.yml
.github/workflows/issue-link.yml

Circleci prtest - trigger testing

---

.circleci/config.yml

Changing ubuntu-1604 to ubuntu-2004 for machine executor

---

tests/network_test.cpp

Fix fluky unit test NetworkTest.node_full_sync
There is a race condition when the last DAG level has more than 1 DAG blocks, the unit test will fail.
Fix by sending a dummy transaction to converge DAG when last DAG level has more than 1 blocks 

chore(unit test): Fix fluky unit test NetworkTest.node_full_sync

---

src/node/full_node.hpp

fix(version): Bump up version

---

.circleci/config.yml

Fixes missing tag when pushing to dockerhub on master branch builds

Fixing missing tag when pushing to master

---

src/config/config.cpp
src/config/config.hpp
src/logger/logger_config.cpp
src/node/full_node.cpp

- change default path were logs should be stored
- change default behavior of log levels

Issue 822/logging

---

config/networks/testnet.json
src/consensus/pbft_manager.cpp
src/network/taraxa_capability.cpp

fix(pbft): PBFT identify leader block need check block validation first

---

config/networks/testnet.json
src/config/config.cpp
src/config/config.hpp
src/consensus/pbft_manager.cpp
src/dag/dag_block_manager.hpp
src/logger/logger_config.cpp
src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp
src/node/full_node.cpp
tests/pbft_manager_test.cpp

Cannot reproduce at local, try fixing running time and waiting time

chore(unit test): Fix pbft manager unit tests timing issue

---

.circleci/config.yml

Push to DockerHub from the develop branch in order to deploy the testnet from the latest develop

chore(deploy): push to DockerHub from develop

---

CMakeLists.txt
CMakeModules/clang_format.cmake
CMakeModules/clang_tidy.cmake

chore(clang-format): restore cmake for clang-format

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp

Give up voted value when the voted value is not valid or have waited 5+ rounds

fix(pbft): Give up voted value

---

src/network/taraxa_capability.cpp
src/transaction_manager/transaction_manager.cpp
src/transaction_manager/transaction_manager.hpp
src/transaction_manager/transaction_queue.cpp
src/transaction_manager/transaction_queue.hpp
tests/p2p_test.cpp

While working on double verification I have noticed that processing of block trxs is kind of mess. This is just small refactor of it

refactor(trx_mngr): refactor processing of block trxs

---

.circleci/config.yml

Fixes issues with some releases when replacing existing tags
Changed the strategy of having one job per binary release to have just one after all binaries were succesfully compiled and tested, making just one upload of the release

changed strategy for creating releases combining both workspaces (mac…… and linux) into one dir

---

.circleci/config.yml
.github/workflows/trigger-ci-on-branch.yml

Enable Triggering circleci builds con commits to master.

Adding GH Action to Trigger build on master branch

---

src/network/taraxa_capability.cpp
src/node/full_node.hpp

fix(syncing): reduce sendBlocks traffic by skipping known blocks

---

tests/network_test.cpp

And also updated and improved the cleanliness of these network tests for next vote broadcast.

fix(network_test): broadcast previous round next votes was being dropped due to not waiting for initial status packet

---

Dockerfile

deletes unneeded files in build docker layer

chore(docker) deletes unneeded files in build docker layer

---

src/consensus/pbft_manager.cpp

fix(pbft): handle edge case of terminating voted value is NULL_BLOCK_HASH

---

config/networks/testnet.json

chore(config): bump testnt dag genesis timestamp

---

config/networks/testnet.json

Reverts Taraxa-project/taraxa-node#864

Revert "chore(config): bump testnt dag genesis timestamp"

---

config/networks/testnet.json
src/node/full_node.hpp

chore: testnet config changes before reset

---

src/cli/testnet_config.hpp
src/node/full_node.hpp

chore: update testnet config header and bump network version for testnet reset

---

src/final_chain/final_chain.cpp

fix(build): match type consistent for Mac build

---

tests/network_test.cpp

Need wait nodes connect to each other. Otherwise will fail sending packet:
https://github.com/Taraxa-project/taraxa-node/blob/develop/src/network/taraxa_capability.cpp#L97

chore(unit test): refactor and fix network unit test transfer_transaction

---

.github/workflows/pr-actions.yml

Github actions reading issue comments were failing on this organization this is to fix it
i tested on my fork and this was not happening. after reading the problem looks to be with the GH token, and it is only required to have the 'rocket' reaction, i think it is non important so i am removing it, please approve and merge to develop so we can continue the work, thanks

removed rocket reaction to fix problem with credentials

---

.circleci/config.yml

chore(build): use llvm for mac builds

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/consensus/vote.cpp
src/consensus/vote.hpp
tests/network_test.cpp
tests/vote_test.cpp

fix(votes): Save and broadcast 2t+1 votes

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp
src/util/thread_pool.cpp
src/util/thread_pool.hpp

feat: add additional thread for processing GetPbftBlockPacket

---

CMakeLists.txt
submodules/CMakeLists.txt

Static build was broken on macOS.

chore(build): fix macos static build

---

src/consensus/block_proposer.cpp
src/consensus/block_proposer.hpp

prevent node proposing same level DAG twice

fix: prevent node proposing same level DAG twice

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/node/full_node.hpp

chore(pbft): implement exponential backoff for advanced steps in round beyond MAX_STEPS

---

src/cli/config.cpp
src/cli/default_config.hpp
src/cli/devnet_config.hpp
src/cli/testnet_config.hpp
src/cli/tools.cpp
src/cli/tools.hpp
src/config/config.cpp
src/config/config.hpp
src/consensus/pbft_manager.cpp
src/network/taraxa_capability.cpp
tests/util_test/conf/conf_taraxa1.json
tests/util_test/conf/conf_taraxa2.json
tests/util_test/conf/conf_taraxa3.json
tests/util_test/conf/conf_taraxa4.json
tests/util_test/conf/conf_taraxa5.json
tests/util_test/util.hpp

new directory layout
```
.
+-- config.json
+-- wallet.json
+-- data/
|   +-- db/
|   +-- logs/
|   +-- net/
```

chore(logs): use correct path for logs

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp

Small improvements to peer class

chore(peers): make peer class more thread-safe

---

src/consensus/vote.cpp
src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp

This is a clean combining of PRs #956 and #959

fix(voting): improves voting behavior, logging, and reduces excessive vote sending

---

src/network/network.cpp
src/network/network.hpp
src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp
tests/network_test.cpp
tests/p2p_test.cpp
tests/util_test/util.hpp

Refactor code around sending/receiving initial status message and making sure that nothing is sent or ignored prior to that

chore: optimize status handshake between nodes

---

src/network/taraxa_capability.cpp
src/transaction_manager/transaction_manager.cpp
src/transaction_manager/transaction_manager.hpp
src/transaction_manager/transaction_queue.cpp
src/transaction_manager/transaction_queue.hpp

should resolve https://github.com/Taraxa-project/taraxa-node/issues/973

fix(trx_queue): switch to shared_ptr instead of iterator

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/network/taraxa_capability.cpp
tests/pbft_manager_test.cpp

fix(pbft): give up on soft voted value if never receive valid dag blocks for it

---

src/config/config.cpp
src/logger/logger_config.cpp
src/logger/logger_config.hpp

because we did not specify `target` directory log cleaning up did not work

fix(logs): fix automatic log clean-up

---

src/consensus/pbft_manager.cpp

fix(pbft): fix consensus mistake in second finishing step

---

.circleci/config.yml

splitted circleci contexts to improve security and separate sensitive variables

chore(circleci): Split circleci contexts to improve security

---

CMakeLists.txt
src/cli/devnet_config.hpp

this should remove badcast exception and also fix config for devnet

chore(devnet): increase NET version & fix devnet config

---

src/network/taraxa_capability.cpp

remove asserts during peers addition as nodes were crashing because of it... Logically it should never happen but it does and there are 2 possible scenarios I can think of:
- onDisconnect was never called so disconnected peer was not removed from peers list and once the node reconnected it sent new initial status packet again -> added to the peers list 
- node for some reason sent second initial status packet even though it was not disconnected
- onConnect->addPendingPeer was processed in threadpool before but onDisconnect->erasePeer was not. So this sequence could be actually reordered due to threadpool delay from:
onDisconnect -> onConnect -> onDisconnect -> onConnect -> onDisconnect
to:
onDisconnect -> onDisconnect -> onConnect  -> onConnect -> onDisconnect

fix(tarcap): call both onConnect->addPendingPeer & onDisconnect->erasePeer outside of threadpool

---

src/network/taraxa_capability.cpp
src/network/taraxa_capability.hpp

Syncing bugfixes

---

.github/workflows/pr-net-cleanup-on-close.yml

Removed env github_oten

---

.github/workflows/pr-net-cleanup-on-close.yml

Changed name of GITHUB_TOKEN secret for GH_TOKEN

---

.github/workflows/pr-net-cleanup-on-close.yml

Testing gh action to auto cleanup prnet after merge, ignore this, delete this branch after merge

---

src/cli/devnet_config.hpp
src/cli/testnet_config.hpp

To improve the speed with which nodes bootstrap to the network.

chore(sync): increase network_sync_level_size from 10 to 25

---

src/storage/db_storage.cpp
src/util/jsoncpp.cpp
src/util/util.hpp
tests/dag_test.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_chain_test.cpp
tests/transaction_test.cpp
tests/vote_test.cpp

resolves https://github.com/Taraxa-project/taraxa-node/issues/753

chore(new): replace new to make_shared/unique where possible

---

.github/workflows/pr-net-cleanup-on-close.yml

Changed the pull request url object to pass

---

.github/workflows/pr-net-cleanup-on-close.yml

Fixed circleci slug on cleanup on close

---

src/network/taraxa_capability.cpp

fix(peer): remove deadlock

---

.github/actions/prnet/action.yml

Fix conditional

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/consensus/vote.cpp
src/consensus/vote.hpp

fix(pbft): remove delays from improper step timeout when restarting and due to vote retrieval from db

---

src/consensus/vote.cpp
src/consensus/vote.hpp
src/node/full_node.cpp

perf(vote_mgr): rebroadcast own next votes after restart during extended partition

---

src/dag/dag_block_manager.cpp
src/network/taraxa_capability.cpp
src/transaction_manager/transaction_manager.cpp

changed DAG block's transaction  processing to multi-query for better performance

perf(dag): improve Dag block transaction processing with multiquery

---

src/consensus/pbft_manager.cpp
src/consensus/vote.cpp

fix(pbft): do not return early from state operations when syncing

---

src/CMakeLists.txt
src/network/tarcap/new_taraxa_capability.cpp
src/network/tarcap/new_taraxa_capability.hpp
src/network/tarcap/node_stats.cpp
src/network/tarcap/node_stats.hpp
src/network/tarcap/packets_handler/syncing_state.hpp

Tarcap summary and send txs

---

src/consensus/pbft_manager.cpp
src/consensus/vote.cpp

Latest consensus improvements

---

src/consensus/vote.cpp
src/network/rpc/Taraxa.cpp
src/network/rpc/Taraxa.h
src/network/rpc/Taraxa.jsonrpc.json
src/network/rpc/TaraxaClient.h
src/network/rpc/TaraxaFace.h

resolves https://github.com/Taraxa-project/taraxa-node/issues/979
request 
```
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"taraxa_getVersion","params": [],"id":1}' http://127.0.0.1:7777
```
response 
```
{"id":1,"jsonrpc":"2.0","result":"1.9.2"}
```

chore(rpc): add new taraxa_getVersion call

---

src/network/rpc/Test.cpp
src/network/rpc/Test.h
tests/full_node_test.cpp

Fix some of fails in a full_node_test including accidentally changed `save_network_to_file test`

chore(tests): fix full_node_test

---

src/consensus/pbft_chain.cpp
src/consensus/pbft_chain.hpp
src/dag/dag_block_manager.cpp
src/final_chain/state_api.cpp
src/final_chain/state_api.hpp
src/network/taraxa_capability.cpp
src/storage/db_storage.cpp
src/storage/db_storage.hpp
src/transaction_manager/transaction_manager.cpp
tests/network_test.cpp

perf(syncing): small change to get PBFT blocks by multiquery

---

src/consensus/pbft_chain.cpp
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/storage/db_storage.cpp
src/storage/db_storage.hpp
tests/full_node_test.cpp

PBFT Never Terminate Cert voted Value

---

src/consensus/vote.cpp
src/consensus/vote.hpp
src/network/taraxa_capability.cpp
tests/crypto_test.cpp

do not verify votes in constructor
resolves https://github.com/Taraxa-project/taraxa-node/issues/1065

perf(votes): do not verify votes in constructor

---

CMakeLists.txt
src/cli/testnet_config.hpp
src/consensus/pbft_manager.cpp

fix(pbft): remove assert checking since previous round next voted value may null block hash

---

src/CMakeLists.txt
tests/pbft_manager_test.cpp
tests/util_test/util.hpp

chore(tests): rework pbft_manager_run_multi_nodes test

---

src/cli/testnet_config.hpp
src/consensus/pbft_manager.cpp
src/network/taraxa_capability.cpp
tests/pbft_manager_test.cpp

Fix consensus issue with giving up soft voted value that could be potentially cert voted

---

src/cli/testnet_config.hpp
src/config/config.hpp
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp

Pbft give up fix

---

src/config/config.hpp

Observed crash in libp2p potentially from having multiple threads.   Testing this as a temporary fix.

chore(network): set network_num_threads default to 1

---

src/consensus/pbft_manager.cpp

fix(pbft): do not next vote soft voted value in second finish if giveup soft voted value is true

---

src/consensus/pbft_manager.cpp
src/network/taraxa_capability.cpp

Fix the requestblocks endless loop fix

---

src/network/taraxa_capability.cpp

Revert pbft gossip suppression change

---

src/cli/devnet_config.hpp
src/cli/testnet_config.hpp

update boot-node ids to actually match bootnodes

chore(config): update bootnode ids

---

src/config/config.hpp
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp

chore(fix): fix for p2p crash and crash on finalize

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp

chore(pbft): Fix dumping error logs

---

.circleci/config.yml

This is to break fix the previous change for an uncaguth issue pushing a cache tag that does not exist anymore
Please approve ASAP

chore(circleci): fix pushing node-cache image

---

.circleci/config.yml

Fixed syntax error in docker image prune
this is a break fix.

chore(circleci): Fixed syntax error for docker image prune

---

src/storage/db_storage.cpp

Dag blocks are stored in column dag_blocks when non executed but once executed they are deleted from that column and added to period_data column. When retrieving blocks there was a bug that we first checked in period_data column and if they are missing then in dag_blocks column. It was possible that between those two db get operations data was deleted from dag_blocks and written to period_data and we would not retrieve the dag block.
Reversing the get order is the fix.

fix: fixed db race condition when getting blocks from two tables

---

.circleci/config.yml

This is to fix a bug where the prnets are not cleaned up correctly

chore(circleci): Fixed missing namespace switch

---

src/storage/db_storage.cpp

Our DB size was huge because we did not clean dag blocks and trxs properly, so we had everything 2x

fix(db): fix issue with removing old blks/trxs

---

CMakeModules/EthUtils.cmake
CMakeModules/scripts/jsonrpcstub.cmake
src/network/rpc/Test.cpp
src/network/rpc/Test.h
src/network/rpc/Test.jsonrpc.json
src/network/rpc/TestClient.h
src/network/rpc/TestFace.h
src/storage/db_storage.cpp
src/storage/db_storage.hpp

API call to get DB columns sizes
```
{
"id": 1,
"jsonrpc": "2.0",
"result": {
"dag_block_period": 50417076,
"dag_blocks": 1228798560,
"dag_blocks_index": 75370346,
"dag_blocks_state": 455590,
"dag_finalized_blocks": 36878919,
"default": 0,
"dpos_proposal_period_levels_status": 4107,
"final_chain_blk_by_number": 11199779,
"final_chain_blk_hash_by_number": 1149502,
"final_chain_blk_number_by_hash": 1146428,
"final_chain_log_blooms_index": 6429167,
"final_chain_meta": 4047,
"final_chain_receipt_by_trx_hash": 306110845,
"final_chain_replay_protection": 0,
"final_chain_transaction_count_by_blk_number": 602068,
"final_chain_transaction_hashes_by_blk_number": 187411265,
"final_chain_transaction_location_by_hash": 274505932,
"next_votes": 31135,
"pbft_block_period": 1144615, …
```

chore(api): api call to get basics statistics from db

---

src/storage/db_storage.cpp
src/storage/db_storage.hpp

Small change that should improve performance in case key is NOT in the DB

chore(db): small perf improvements for checking if key is in DB

---

src/aleth/libp2p/Host.cpp

Fix for stack trace from weekend

chore(p2p): fix another crash in host.cpp

---

src/cli/testnet_config.hpp

chore(testnet): bump testnet dag genesis

---

src/consensus/pbft_chain.cpp
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/consensus/vote.cpp
src/consensus/vote.hpp
src/dag/dag_block_manager.cpp
src/node/full_node.cpp
src/storage/db_storage.cpp
src/storage/db_storage.hpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_manager_test.cpp
tests/vote_test.cpp

Synced Next Votes Bundle Verification

---

src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/network/sync_block.cpp
src/network/sync_block.hpp

PR for testnet for the order hash issue

fix: order hash

---

src/cli/testnet_config.hpp

chore(testnet): increase dag timestamp

---

src/CMakeLists.txt
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/consensus/sync_block.hpp
src/consensus/sync_queue.cpp
src/consensus/sync_queue.hpp

This should fix latest issues on testnet described by #1189

chore(syncing): fix condition for pushing syncing blocks

---

src/CMakeLists.txt
src/cli/testnet_config.hpp
src/consensus/pbft_manager.cpp
src/consensus/pbft_manager.hpp
src/consensus/sync_block.hpp
src/consensus/sync_queue.cpp
src/consensus/sync_queue.hpp

Fix for syncing period

---

src/network/network.cpp
src/network/network.hpp
src/network/rpc/Test.cpp
src/network/rpc/Test.h
src/network/rpc/Test.jsonrpc.json
src/network/rpc/TestClient.h
src/network/rpc/TestFace.h
src/network/tarcap/packets_handlers/common/packet_handler.cpp
src/network/tarcap/stats/node_stats.cpp
src/network/tarcap/stats/packets_avg_stats.cpp
src/network/tarcap/stats/packets_avg_stats.hpp
src/network/tarcap/stats/packets_stats.cpp
src/network/tarcap/stats/packets_stats.hpp

feat(tarcap): new rpc call get_packets_stats implemented

---

for_devs/README.md
for_devs/local-net

Enable using script for local-net deployment to redeploy the same network with adjusted configs...
`./for_devs/local-net start --boot-nodes 3 --rpc-nodes 1 --tps 1 ./cmake-build-debug/bin/taraxad`

chore: make local net redeployable

---

libraries/core_libs/CMakeLists.txt
programs/taraxad/CMakeLists.txt
submodules/CMakeLists.txt
tests/CMakeLists.txt

https://github.com/Taraxa-project/taraxa-node/issues/1203

Fix linux static build

---

Dockerfile
scripts/taraxa-sign.py

adds signing script that will be used both internally for delegation and externally to prove node ownership by community

chore(devops): adds signing script

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

chore(pbft): cleanup previous round votes when move to a new round

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/config.hpp
libraries/config/src/config.cpp
libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp

Introduce deep syncing method, to skip specific packet processing. Please especially check this `filterSyncIrrelevantPackets`

chore(syncing): introduce deep syncing

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/stats/node_stats.cpp
libraries/types/vote/include/vote/vote.hpp
libraries/types/vote/src/vote.cpp

Unify vote validation function

chore(vote): clean up vote validation

---

libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_syncing_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
libraries/types/vote/include/vote/vote.hpp

Start syncing even if we are just one block behind

chore(syncing): change condition to restart syncing

---

libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp

Just fix after @JakubFornadel comments on last PR #1276

chore(votes): fix for previous commit

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

Cherry pick from develop branch

chore(pbft): In propose block, only use weigited index 0 for VRF sortition

---

libraries/core_libs/storage/src/storage.cpp

https://github.com/Taraxa-project/taraxa-node/issues/1291

chore(db): check if db iter is valid

---

libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp

fix race condition after latest PR and also implement move semantics

chore(syncing): fix race condition after latest PR

---

CMakeLists.txt
libraries/aleth/libp2p/CMakeLists.txt
libraries/cli/CMakeLists.txt
libraries/config/CMakeLists.txt
libraries/core_libs/CMakeLists.txt
libraries/logger/CMakeLists.txt
libraries/types/dag_block/CMakeLists.txt
libraries/types/pbft_block/CMakeLists.txt
libraries/types/transaction/CMakeLists.txt
libraries/types/vote/CMakeLists.txt
libraries/vdf/CMakeLists.txt
programs/taraxa-bootnode/CMakeLists.txt
programs/taraxad/CMakeLists.txt
tests/CMakeLists.txt

We have lot of complicated dependencies, this PR is trying to clean up current structure
Dependency graph after changes

chore(building): try to clean-up library dependencies

---

libraries/core_libs/storage/include/storage/db_utils.hpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/include/storage/uint_comparator.hpp
libraries/core_libs/storage/src/storage.cpp
tests/sortition_test.cpp

Add custom UINT rocksdb comparator

Uint rocksdb comparator

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/storage/include/storage/uint_comparator.hpp

https://github.com/Taraxa-project/taraxa-node/issues/1290

fix(pbft): fix atomic issue for saving next votes with PBFT round and step

---

libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp

After sending pbft block to a peer mark pbft block as known for that peer. This ensures that same pbft block is only sent once to connected peer.

chore: pbft packet impr

---

libraries/cli/include/cli/devnet_config.hpp

chore: revert devnet timestamp back to the original value

---

libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/types/vote/src/vote.cpp

After deep syncing, node could receive votes but still behind, may don't have vote sender state in table

checkout staking exist before vote verification

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/stats/node_stats.cpp
tests/state_api_test.cpp
tests/vote_test.cpp

As we talked yesterday about this, we use wrong parameter for propose_block vote type. This PR is fixing it.
If we are ok with that we should prepare hardfork for testnet

chore(votes): change parameters for propose_block vote

---

docker-entrypoint.sh

adds taraxa-bootnode option in entrypoint

chore(docker): adds taraxa-bootnode option in entrypoint

---

libraries/core_libs/consensus/include/pbft/block_proposer.hpp
libraries/core_libs/consensus/src/pbft/block_proposer.cpp

Do not propose stale blocks if any new DAG block appeared in the network

fix: stale blocks

---

libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp

Remove any finalized block from non finalized on startup.
Add additional check if block has been finalized on adding blocks to DAG/non finalized blocks

fix: duplicate non finalized blocks

---

libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp

chore: stale difficulty efficiency

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/common/include/common/constants.hpp
libraries/config/src/chain_config.cpp
libraries/core_libs/consensus/include/dag/sortition_params_manager.hpp
libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
libraries/vdf/include/vdf/config.hpp
libraries/vdf/src/config.cpp
libraries/vdf/src/sortition.cpp
tests/crypto_test.cpp
tests/full_node_test.cpp
tests/sortition_test.cpp
tests/util_test/util.hpp

Remove code needed for hardforks and move some params to config to make it cleaner

Remove hardforks

---

libraries/cli/include/cli/default_config.hpp

feat: change pbft lambda time to 6 seconds

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
tests/sortition_test.cpp

PBFT proposal block rate depends on stakes, not every delegation node has same rate anymore

PBFT proposal blocks rate on mainnet

---

docker-entrypoint.sh

adds advertised ip flag if env var is set

Advertised ip

---

libraries/cli/include/cli/default_config.hpp

Adjust config values

---

CMakeLists.txt
libraries/cli/include/cli/default_config.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp

Mainnet node version update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/epic_issue.md
.github/ISSUE_TEMPLATE/small_task.md
.github/pull_request_template.md

New issues & PR templates that will be used togeter with github projects

docs: new PR/issues templates

---

.circleci/config.yml

Make circleci able to set rpc nodes load balancer
This temporary is pointing to a different branch
or is for additional features. Patch is for bug fixes.

chore(ci): Enable ips rpcnodes

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

Revert lambda exponential back off

Revert lambda exponential back off

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp

fix https://github.com/Taraxa-project/taraxa-node/issues/1475

Revert PBFT Exponential Backoff For Develop Branch

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

If have seen enough (2t+1) soft votes in the current round, PBFT should rebroadcast them in second finish state
fix https://github.com/Taraxa-project/taraxa-node/issues/1488

PBFT Rebroadcast Soft Votes

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/rpc/Test.h
libraries/core_libs/network/rpc/Test.jsonrpc.json
libraries/core_libs/network/rpc/TestClient.h
libraries/core_libs/network/rpc/TestFace.h
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
libraries/core_libs/node/src/node.cpp
libraries/types/transaction/include/transaction/transaction.hpp
tests/dag_test.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_chain_test.cpp
tests/transaction_test.cpp
tests/util_test/samples.hpp

chore(trxs): correct transaction validation

---

libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
libraries/core_libs/consensus/include/transaction_manager/transaction_queue.hpp
libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
libraries/core_libs/consensus/src/transaction_manager/transaction_queue.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/transaction_test.cpp

Transaction prio queue

---

conanfile.py

chore(conan): fix latest change in conan recipes

---

libraries/common/include/common/encoding_rlp.hpp

We are now checking rlp size in both directions actual:
- rlp.itemsCount() < expected_size 
- and also rlp.itemsCount() > expected_size

fix: fix rlp encoding/decoding fixed items count requirement

---

libraries/common/include/common/util.hpp
libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/replay_protection_service.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
libraries/types/dag_block/src/dag_block.cpp
libraries/types/dag_block/src/proposal_period_levels_map.cpp
libraries/types/pbft_block/src/pbft_block.cpp
libraries/types/pbft_block/src/sync_block.cpp
libraries/types/transaction/include/transaction/transaction.hpp
libraries/types/transaction/src/transaction.cpp
libraries/types/vote/include/vote/vote.hpp
libraries/types/vote/src/vote.cpp
libraries/vdf/src/sortition.cpp
tests/final_chain_test.cpp
tests/network_test.cpp
tests/p2p_test.cpp
tests/tarcap_threadpool_test.cpp
tests/transaction_test.cpp

chore: pbft transaction ordering

---

libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp

fixes https://github.com/Taraxa-project/taraxa-node/issues/1542

chore: fix move bug in vote sync handler

---

libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp

chore: remove assert from getting non-finalized trxs

---

libraries/config/include/config/chain_config.hpp
libraries/config/src/chain_config.cpp
tests/full_node_test.cpp
tests/hardfork_test.cpp
tests/util_test/util.hpp

fix(config): remove excess hardcoded account

---

tests/crypto_test.cpp

chore: increase test threshold because it failed sometimes

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/config.hpp
libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/stats/node_stats.cpp
libraries/core_libs/node/src/node.cpp
tests/dag_test.cpp
tests/network_test.cpp
tests/pbft_chain_test.cpp

chore: move dag validation to packet handler

---

libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
libraries/core_libs/consensus/include/dag/sortition_params_manager.hpp
libraries/core_libs/consensus/include/pbft/pbft_chain.hpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
tests/dag_block_test.cpp
tests/network_test.cpp
tests/pbft_manager_test.cpp
tests/sortition_test.cpp
tests/util_test/util.hpp

PBFT produce blocks with NULL HASH DAG block as anchor when there is no new DAG blocks generate

PBFT Produce Blocks with NULL Anchor

---

libraries/cli/CMakeLists.txt
libraries/cli/include/cli/mainnet_config.hpp
libraries/cli/src/tools.cpp

chore: re-introduce default config

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1468

PBFT Exponential Backoff in steps

---

libraries/core_libs/storage/src/storage.cpp

fix: cleanup efficiency

---

libraries/cli/include/cli/testnet_config.hpp

chore: return back RPC nodes to speed-up discovery after restart

---

libraries/cli/include/cli/testnet_config.hpp

chore: return back RPC nodes to speed-up discovery after reset

---

tests/crypto_test.cpp

chore: changed values to test is stable

---

tests/full_node_test.cpp
tests/network_test.cpp

EVM branch https://github.com/Taraxa-project/taraxa-evm/pull/35
fixes: #1550

chore: fail on overflow in dpos contract

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/replay_protection_service.hpp
libraries/core_libs/consensus/include/final_chain/state_api_data.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/replay_protection_service.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/rpc/eth/data.hpp
libraries/types/transaction/include/transaction/transaction.hpp
libraries/types/transaction/src/transaction.cpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1558
Fix in taraxa-evm https://github.com/Taraxa-project/taraxa-evm/pull/36/

fix: use u256 for transaction nonce value

---

for_devs/run_test_in_loop.sh

test: added script for running tests in infinite loop

---

libraries/common/include/common/util.hpp
libraries/common/src/util.cpp
libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/dag_block_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/stats/packets_stats.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/network_test.cpp

Handle setting peer as malicious and disconnecting peer for various reasons when dag block verification fail

dag block verification error handling

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/node/src/node.cpp
libraries/types/vote/include/vote/vote.hpp
tests/vote_test.cpp

chore: improve round calculation from votes

---

libraries/cli/include/cli/default_config.hpp

chore: change HF block number

---

libraries/config/src/config.cpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/get_pbft_sync_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1561

fix: add pbft chain synced flag

---

CMakeLists.txt
libraries/cli/include/cli/devnet_config.hpp

chore: add devnet RPC nodes

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/types/vote/include/vote/vote.hpp
tests/full_node_test.cpp
tests/pbft_chain_test.cpp
tests/pbft_manager_test.cpp
tests/py/common/chain_tester/chain_tester.py
tests/util_test/util.hpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1599

Refactor: refactor PBFT for no NULL hash proposal blocks

---

libraries/core_libs/storage/src/storage.cpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1647

Mac build for develop branch

---

libraries/core_libs/consensus/include/transaction/gas_pricer.hpp
libraries/core_libs/consensus/src/transaction/gas_pricer.cpp
libraries/core_libs/node/src/node.cpp

chore: add support of light node to gas pricer

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/src/chain_config.cpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/pbft_manager_test.cpp
tests/py/common/chain_tester/chain_tester.py
tests/py/common/chain_tester/misc.py
tests/py/common/node/node.py
tests/py/tests/test_ethereum_jsonrpc.py
tests/util_test/util.hpp

chore: enable strict ordering of transactions

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/boot-node.yaml
charts/taraxa-node/templates/consensus-node.yaml
charts/taraxa-node/templates/taraxa-node.yaml
charts/taraxa-node/values.yaml

nodeSelector per node type

---

.circleci/config.yml
.gitignore
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/_helpers.tpl
charts/taraxa-node/templates/boot-node-service.yaml
charts/taraxa-node/templates/boot-node.yaml
charts/taraxa-node/templates/boot-nodes-services-loadbalancer.yaml
charts/taraxa-node/templates/consensus-node-service.yaml
charts/taraxa-node/templates/consensus-node.yaml
charts/taraxa-node/templates/explorer-check.yaml
charts/taraxa-node/templates/initconfig-boot-node.yaml
charts/taraxa-node/templates/initconfig-consensus-node.yaml
charts/taraxa-node/templates/initconfig-node.yaml
charts/taraxa-node/templates/node-status-script.yaml
charts/taraxa-node/templates/port-check.yaml
charts/taraxa-node/templates/secrets.yaml
charts/taraxa-node/templates/taraxa-node-ingress.yaml
charts/taraxa-node/templates/taraxa-node-service.yaml
charts/taraxa-node/templates/taraxa-node.yaml
charts/taraxa-node/templates/taraxa-nodes-services-loadbalancer.yaml
charts/taraxa-node/templates/test-script-role.yaml
charts/taraxa-node/templates/test-script-rolebinding.yaml
charts/taraxa-node/templates/test-script-serviceaccount.yaml
charts/taraxa-node/templates/tests/helmtestfolder.yaml
charts/taraxa-node/values.yaml

Helm chart for taraxa-node

---

libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp

Again we did move an object inside 2 loops

chore: incorrect move of vote

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/boot-nodes-services-loadbalancer.yaml
charts/taraxa-node/values.yaml

added annotations to boot node svc

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp

Release/testnet v1.0.3

---

libraries/cli/include/cli/testnet_config.hpp

updated timestamp

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp

Fixes https://github.com/Taraxa-project/taraxa-node/issues/1711

chore: enable nonce skipping

---

libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp

On stopping the node, there was a chance to get into endless loop of calling restartSyncing for the same peer. Fix makes sure that restartSyncingPbft(true) is called only if peer actually got disconnected. This issue was causing full_node_test to sometimes run for a long time and the build on circleci would timeout because of it.

fix: restart syncing

---

libraries/common/include/common/event.hpp

While moving my stuff to new PC I found an issue while building our repo

chore: fix building under newer clang

---

libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp

fix: make snapshots_enabled flag atomic

---

CMakeLists.txt
libraries/core_libs/consensus/src/final_chain/final_chain.cpp

Merging https://github.com/Taraxa-project/taraxa-node/pull/1726 based on master to testnet through new branch(due to conflicts)

Testnet hotfix/v1.0.2 fast syncing

---

libraries/core_libs/consensus/src/final_chain/final_chain.cpp

Merging [hotfix branch](https://github.com/Taraxa-project/taraxa-node/pull/1726) based on master to develop through new branch(due to conflicts)

Develop hotfix/v1.0.2 fast syncing

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/include/final_chain/state_api_data.hpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/final_chain/state_api_data.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/network/rpc/Taraxa.cpp
libraries/core_libs/network/rpc/Taraxa.h
libraries/core_libs/network/rpc/Taraxa.jsonrpc.json
libraries/core_libs/network/rpc/TaraxaClient.h
libraries/core_libs/network/rpc/TaraxaFace.h
libraries/core_libs/network/src/tarcap/stats/node_stats.cpp
libraries/core_libs/node/src/node.cpp
tests/CMakeLists.txt
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/hardfork_test.cpp
tests/pbft_manager_test.cpp
tests/rpc_taraxa_test.cpp
tests/state_api_test.cpp
tests/util_test/util.hpp

chore: switch to new dpos2.0

---

libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/common/exceptions.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_votes_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/pbft_block_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_votes_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/vote_test.cpp

Fix https://github.com/Taraxa-project/taraxa-node/issues/1700

Send votes in bundle of maximum N votes

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/types/vote/include/vote/vote.hpp
libraries/types/vote/include/vote/vrf_sortition.hpp

Fixed https://github.com/Taraxa-project/taraxa-node/issues/1760

Add comments for vote module

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/mainnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/state_api_config.cpp
tests/full_node_test.cpp

EVM PR https://github.com/Taraxa-project/taraxa-evm/pull/53

chore: add configuration for tokenomics

---

libraries/core_libs/consensus/include/final_chain/rewards_stats.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/rewards_stats.cpp

fix: Process rewards stats also during finalchain init

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/mainnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/chain_config.cpp
libraries/config/src/config.cpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/node/src/node.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/hardfork_test.cpp
tests/state_api_test.cpp
tests/util_test/util.hpp

chore: read dpos config paramas from config

---

for_devs/local-net
libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/mainnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/chain_config.cpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/src/final_chain/state_api_data.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/util_test/util.hpp

https://github.com/Taraxa-project/taraxa-evm/pull/71

feat: new genesis structure for initial validators

---

libraries/core_libs/consensus/include/dag/dag.hpp
libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/node/include/node/node.hpp
libraries/core_libs/node/src/node.cpp
tests/dag_test.cpp

Fixed https://github.com/Taraxa-project/taraxa-node/issues/1789
Fixed https://github.com/Taraxa-project/taraxa-node/issues/1650

Remove log_time_

---

libraries/core_libs/network/rpc/Test.cpp

Fixed https://github.com/Taraxa-project/taraxa-node/issues/1772

Fix RPC get_all_nodes Return Format

---

libraries/cli/include/cli/default_config.hpp
libraries/cli/include/cli/devnet_config.hpp
libraries/cli/include/cli/mainnet_config.hpp
libraries/cli/include/cli/testnet_config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/chain_config.cpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_manager_test.cpp
tests/py/common/node/node.py
tests/state_api_test.cpp
tests/transaction_test.cpp
tests/util_test/conf/conf_taraxa1.json
tests/util_test/conf/conf_taraxa2.json
tests/util_test/conf/conf_taraxa3.json
tests/util_test/conf/conf_taraxa4.json
tests/util_test/conf/conf_taraxa5.json
tests/util_test/node_dag_creation_fixture.hpp
tests/util_test/samples.hpp
tests/util_test/util.hpp

Remove gas flag

---

submodules/CMakeLists.txt
tests/CMakeLists.txt

chore: try to enable all tests

---

conanfile.py
libraries/aleth/libp2p/Host.cpp

Fixes: #1691
https://github.com/Taraxa-project/taraxa-evm/pull/82/f

chore: update projects dependencies

---

libraries/core_libs/consensus/include/dag/block_proposer.hpp
libraries/core_libs/consensus/src/dag/block_proposer.cpp
tests/full_node_test.cpp

chore: remove async from vdf computation

---

.circleci/config.yml

fix for circleci

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/dag/block_proposer.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp

chore: slightly improve locking when adding reward vote

---

libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp

feat: use exist method to check if object is in the DB

---

libraries/config/include/config/config.hpp
libraries/config/src/config.cpp
libraries/core_libs/node/src/node.cpp

chore: check if correct secrets were provided

---

tests/network_test.cpp

chore: re-enable transfer_lot_of_blocks test

---

libraries/config/src/config.cpp
tests/network_test.cpp

chore: fix node_sync2 test

---

CMakeLists.txt
doc/building.md
submodules/CMakeLists.txt

build: reguire cmkae >= 3.20 + adjusted building doc for ubuntu 20.04

---

libraries/cli/include/cli/config_jsons/default.json
libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/mainnet.json
libraries/cli/include/cli/config_jsons/testnet.json
libraries/config/include/config/state_api_config.hpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/rewards_stats.hpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/rewards_stats.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
libraries/core_libs/node/src/node.cpp
libraries/types/pbft_block/include/pbft/period_data.hpp
libraries/types/pbft_block/src/period_data.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/transaction_test.cpp

EVM PR https://github.com/Taraxa-project/taraxa-evm/pull/87

feat: add vote rewards

---

libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
libraries/core_libs/network/src/tarcap/threadpool/packets_blocking_mask.cpp
libraries/types/dag_block/include/dag/dag_block.hpp
libraries/types/dag_block/src/dag_block.cpp
tests/tarcap_threadpool_test.cpp

See description in linked issue

refactor: fix packets wrong format

---

libraries/cli/include/cli/config_jsons/devnet.json

dag limit is now 21000 * 10000
pbft limit is dag limit * 10

chore: increase dag and pbft gas limit on devnet

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/types/vote/include/vote/vrf_sortition.hpp
libraries/types/vote/src/vrf_sortition.cpp
tests/crypto_test.cpp

1 of the possible solutions, but we should definitely debug why  `const vrf_wrapper::vrf_output_t& output` in `HashableVrf` gets overidden

fix: fix leader selection

---

libraries/types/vote/include/vote/vote.hpp

Vote values ref

---

libraries/core_libs/network/rpc/eth/Eth.cpp

Fixes #1844 
EVM PR https://github.com/Taraxa-project/taraxa-evm/pull/92

Fix eth call

---

libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp

When sending transactions in dag block packet handler kMaxTransactionsInPacket limit was not used which would make us fail such a packet on receiving end and mark node as malicious.

fix: sending transactions

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

On regossiping soft votes also regossip reward votes if needed

chore: reward votes gossip improvement

---

libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp

fix: remove weight check in pbft syncing

---

libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp

Fix receipt status

---

libraries/types/transaction/include/transaction/transaction.hpp
libraries/types/transaction/src/transaction.cpp
tests/CMakeLists.txt
tests/full_node_test.cpp
tests/transaction_test.cpp

fix: describe RLP parsing fail

---

for_devs/local-net

chore: fix local net script

---

.circleci/config.yml

circle ci config from develop to master

---

libraries/cli/include/cli/config_jsons/mainnet.json
libraries/cli/include/cli/config_jsons/testnet.json

chore: lower number of snapshots

---

libraries/core_libs/consensus/src/transaction/transaction_manager.cpp

chore: fix gas estimation on faild transaction

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/node-status-script.yaml

added channel slack notifications

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/include/pbft/step/certify.hpp
libraries/core_libs/consensus/include/pbft/step/filter.hpp
libraries/core_libs/consensus/include/pbft/step/finish.hpp
libraries/core_libs/consensus/include/pbft/step/polling.hpp
libraries/core_libs/consensus/include/pbft/step/propose.hpp
libraries/core_libs/consensus/include/pbft/step/step.hpp
libraries/core_libs/consensus/include/pbft/utils.hpp
libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/pbft/step/certify.cpp
libraries/core_libs/consensus/src/pbft/step/filter.cpp
libraries/core_libs/consensus/src/pbft/step/finish.cpp
libraries/core_libs/consensus/src/pbft/step/polling.cpp
libraries/core_libs/consensus/src/pbft/step/propose.cpp
libraries/core_libs/consensus/src/pbft/step/step.cpp
libraries/core_libs/consensus/src/pbft/utils.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
libraries/core_libs/node/src/node.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_manager_test.cpp
tests/vote_test.cpp

Separated steps specific logic into different classes with common base class `Step` . Some of common logic is in this `Step` class.

feat: separate step logic from manager into specific classes

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/consensus-node.yaml
charts/taraxa-node/templates/initconfig-consensus-node.yaml
charts/taraxa-node/templates/initconfig-node.yaml
charts/taraxa-node/templates/taraxa-node.yaml

Generate config for non-standard networks in python (initial phase)
Changed from bash into python part of config generation.
Changed config generation for:
- initial validators

rewrite config initial phase in python

---

libraries/aleth/libdevcore/CommonJS.h

Currently we have wrong response in case of empty data:
```
[rpc-node-0]     0x00007f2ddcff9640 RPC [2022-08-05 14:42:45.837026] TRACE: POST Read: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0",false],"id":16}
[rpc-node-0]     0x00007f2ddcff9640 RPC [2022-08-05 14:42:45.837324] TRACE: POST Write: {"id":16,"jsonrpc":"2.0","result":{"author":"0x0000000000000000000000000000000000000000","difficulty":"0x0","extraData":"","gasLimit":"0x1fffffffffffff","gasUsed":"0x0","hash":"0x91398fa807086c349f829b61b87663f57f671c6a53459bae398589bf2f5598f9","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

chore: fix RPC response on empty data

---

libraries/aleth/libdevcore/CommonJS.h

Testnet rpc fix

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/initconfig-consensus-node.yaml
charts/taraxa-node/templates/initconfig-node.yaml

- added changelog
- update chart version
- replace devnet, testnet and mainnet chain ids
We need to support new chain IDs with prefixes
Update to helm chart
- Added changelog 
- Changed ids:
- 1 -> 841
- 2 -> 842
- 3 -> 843

Support change of chain IDs with prefix

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp

On reloading reward votes from database, weight needs to be calculated correctly using the correct period

fix: reward votes weight

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp

chore: propagate correct reward votes

---

libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/consensus/src/transaction/transaction_queue.cpp

We had 2 UB, when we used iterator after erase

chore: fix UB on erase

---

.circleci/config.yml

enable faucet for prnets

---

libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp

chore: validate reward votes on first syncing packet

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
tests/pbft_chain_test.cpp

Only reset cert vote value if it is pushed in chain.
Do not give up on cert vote value

chore: unique cert value in period

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
tests/vote_test.cpp

chore: add support for next votes period

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/node-status-script.yaml

Merge of helm-chart from development to master

Helm Chart version 0.1.8

---

libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/rpc/Test.h

chore: use correct chain ID for smoke tests

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

If cert_voted_block_for_round_ is pushed into chain next vote for NULL value

chore: vote null if cert voted value pushed

---

libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp

chore: refactor period & round checking when processing votes

---

charts/taraxa-node/templates/initconfig-node.yaml

iterate over consensus node not rpc node

---

libraries/cli/include/cli/config_jsons/default.json
libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/mainnet.json
libraries/cli/include/cli/config_jsons/testnet.json
libraries/config/include/config/config.hpp
libraries/config/include/config/state_api_config.hpp
libraries/config/src/config.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_votes_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/get_votes_sync_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/votes_sync_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/get_votes_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/util_test/util.hpp

feat: not accept votes with round or step bigger then expected. check sync votes bundle has same step and round

---

libraries/core_libs/storage/src/storage.cpp

fix: fixed column name when removing last block cert votes

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
tests/full_node_test.cpp

chore: broadcast next votes only if round > 1

---

libraries/core_libs/consensus/include/dag/dag.hpp
libraries/core_libs/consensus/include/dag/dag_manager.hpp
libraries/core_libs/consensus/src/dag/dag.cpp
libraries/core_libs/consensus/src/dag/dag_manager.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
tests/dag_test.cpp

- Improve getGhostPath code
- do not try to get the path if anchor == NULL_BLOCK_HASH

Small improvements

---

for_devs/local-net
libraries/cli/include/cli/config.hpp
libraries/cli/src/config.cpp
libraries/config/include/config/config.hpp
libraries/core_libs/network/rpc/Eth.jsonrpc.json
libraries/core_libs/network/rpc/EthClient.h
libraries/core_libs/network/rpc/EthFace.h
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/rpc/eth/Eth.h
libraries/core_libs/node/include/node/node.hpp
libraries/core_libs/node/src/node.cpp
tests/util_test/util.hpp

#1905 
1. Removed `eth_sendTransaction` method. 
2. Added flag `--enable-test-rpc` to node which enables Test API that is now disabled by default.

Fix rpc calls

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

When verifying pbft block there is no need to check for finalized transactions in db. We only pull non-finalized transactions and order_hash verifies validity and order of transactions

chore: optimize pbft block verification

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
tests/network_test.cpp
tests/vote_test.cpp

Fixes for multiple bugs:
- we never cleaned previous round next votes when moving to the next period
- firstFinish_ step: 
a) else if condition would pass for round == 1, which it should not. 
b) wrongly used previous_round_next_voted_value_.first == NULL_BLOCK_HASH in conditions as previous_round_next_voted_value_ should never be NULL_BLOCK_HASH -> these condition probably did not work correctly as NULL_BLOCK_HASH was default, but this variable should have either some specific hash or nothing
- secondFInish step: 
a) wrongly used previous_round_next_voted_value_.first == NULL_BLOCK_HASH in conditions as previous_round_next_voted_value_ should never be NULL_BLOCK_HASH -> these condition probably did not work correctly
b) it used if else condition but it was supposed to be if if condition

fix: pbft consensus fixes -> make it behave according to the paper

---

libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp

Revert "fix: disable votes ddos protection to test steps syncing"

---

doc/building.md

Add `rapidjson` dependency to installation commands
Related to #1974

chore: update doc/building.md

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml

- Adds changelog messages
- Increments chart version

chore: increments chart version

---

libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp

Increase known transactions cache to 300k

chore: increase known trx cache

---

.circleci/config.yml

- build-and-deploy-image for all branched and tags
- push image to docker hub

Build docker image for tags

---

.circleci/config.yml

- fix build docker image
- tag latest
- reorganise

Fix build for tags

---

.circleci/config.yml

do not force push helm chart (master)

---

.circleci/config.yml

do not force push chart (develop)

---

libraries/cli/include/cli/config_jsons/default.json
libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/mainnet.json
libraries/cli/include/cli/config_jsons/testnet.json
libraries/config/include/config/config.hpp
libraries/config/src/config.cpp
libraries/core_libs/consensus/include/final_chain/cache.hpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/src/tarcap/stats/node_stats.cpp
libraries/core_libs/node/src/node.cpp
tests/CMakeLists.txt
tests/cache_test.cpp
tests/final_chain_test.cpp
tests/pbft_manager_test.cpp
tests/transaction_test.cpp

Cache final chain data

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/votes_sync_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
tests/network_test.cpp

Revert "feat: process VotesSyncPacket only from the nodes we requested"

---

tests/full_node_test.cpp

chore: disable graphql test

---

libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp

Validation that is removed in this PR is based on checking peer object pbft_chain_size and peer round. These values are updated in status packets and we cannot do validation against values that might be obsolete because in between status messages round and chain size can change.
Currently we often do not gossip votes to a lot of nodes because we hit this condition which usually causes pbft progress to be stalled and instead of progressing in one round we usually only progress after couple of rounds.
I am not sure if this type of validation is needed at all but if it is needed some better solution needs to be created because the current one was not working correctly.

fix: vote gossip

---

libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp

Fix race condition when round changes at the time receiving previous round next block

fix: previous round next vote processing

---

libraries/core_libs/consensus/src/final_chain/rewards_stats.cpp

Before this change for rewards calculations we was counting transactions that unique for the block, but included in previous blocks

fix: unique transactions count rewards calculations

---

libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp

when retrying connection to boot nodes, resolve the IP in every retry

chore: boot nodes retries

---

tests/final_chain_test.cpp

fix: fix setting nonce based on tx nonce

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

chore: remove votes count code

---

libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/types/transaction/src/transaction.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/pbft_manager_test.cpp
tests/transaction_test.cpp
tests/util_test/node_dag_creation_fixture.hpp
tests/util_test/samples.hpp
tests/util_test/util.hpp

https://github.com/Taraxa-project/taraxa-evm/pull/99

fix: nonce related issues 

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

Remove sorting from pbft manager run

fix: remove sort from run

---

libraries/core_libs/network/rpc/eth/Eth.cpp
tests/CMakeLists.txt
tests/full_node_test.cpp
tests/rpc_test.cpp

Add gas estimation fix release

---

doc/RPC.md
libraries/cli/include/cli/config_jsons/default.json
libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/mainnet.json
libraries/cli/include/cli/config_jsons/testnet.json
libraries/config/include/config/state_api_config.hpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/types/transaction/include/transaction/transaction.hpp
tests/dag_block_test.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/pbft_manager_test.cpp
tests/py/common/chain_tester/misc.py
tests/py/common/node/node.py
tests/state_api_test.cpp
tests/transaction_test.cpp
tests/util_test/conf/conf_taraxa2.json
tests/util_test/node_dag_creation_fixture.hpp
tests/util_test/util.hpp

Need to be reviewed and merged first https://github.com/Taraxa-project/taraxa-evm/pull/102
#2082

Remove nonce check disabling

---

.circleci/config.yml

- separate helm builds and core taraxa-node builds
- separate release builds from development builds
**Workflows**:
- `build-docker-image`:
- _description_: builds **development docker image** of`taraxa-node`, test and publish to **GCR**
- _triggers_: every commit in branch, apart from branches related to helm charts (`chart/`, `chore/chart-`, `fix/chart-`, `feature/chart-`)
- `release-docker-image`:
- _description_: 
- _triggers_: tags:
- `vX.Y.Z`
- `vX.Y.Z-beta` 
- `build-helm-chart`:
- _description_: builds and publish **development version of helm chart** (publish versions `X.Y.Z-sha.<short_commit_sha>` taken from Chart.yaml in combination with short commit sha, i.e. `0.1.1-sha.9a93ea9`)
- _triggers_: every commit in branch with PR starting with:
- `chart/`
- `chore/chart-`
- …

Redesign Circle Ci pipelines

---

.circleci/config.yml

The same what here: https://github.com/Taraxa-project/taraxa-node/pull/2110
but for `release/v1.1.0` branch

circleci for release/* branch

---

.circleci/config.yml

The same what here: https://github.com/Taraxa-project/taraxa-node/pull/2110
but for `testnet` branch

circle ci for testnet branch

---

.circleci/config.yml

The same what here: https://github.com/Taraxa-project/taraxa-node/pull/2110
but for `develop` branch

circleci for develop branch

---

.circleci/config.yml

align ci config

---

tests/final_chain_test.cpp
tests/py/common/chain_tester/chain_tester.py

https://github.com/Taraxa-project/taraxa-evm/pull/104
#2108

feat: spend gas of transactions failed because of ConsensusErr

---

libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/rpc/jsonrpc_http_processor.cpp
tests/rpc_test.cpp

fixes: #2103
https://github.com/Taraxa-project/taraxa-evm/pull/105

chore: return error msg on RPC call

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/rpc/eth/Eth.h
libraries/core_libs/node/src/node.cpp
tests/dag_block_test.cpp
tests/final_chain_test.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/rpc_test.cpp
tests/util_test/node_dag_creation_fixture.hpp
tests/util_test/util.hpp

https://github.com/Taraxa-project/taraxa-evm/pull/106/
fixed #2132

Max gas limit

---

libraries/core_libs/consensus/src/transaction/transaction_queue.cpp

Minor changes related to transactions ordering

chore: trx sorting minor cleanup

---

libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/testnet.json

chore: add taraxa_devs account for devnet and testnet

---

.circleci/config.yml

Use current helm chart of taraxa-node
Replaces repo of chart.
Uses chart from the same repo what main taraxa-node

fix: prnet deploy current chart

---

.circleci/config.yml

Equal config for Circle Ci on `master` branch
Brough Circle Ci config from develop

helm chart for prnets

---

libraries/core_libs/network/rpc/eth/Eth.cpp
tests/rpc_test.cpp

fix: eth_call default gas and gas_price values

---

libraries/core_libs/consensus/include/final_chain/rewards_stats.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/rewards_stats.cpp

#2134 
https://github.com/Taraxa-project/taraxa-evm/pull/107 should be reviewed and merged first

feat: equally reward dag blocks with at least one unique transaction

---

libraries/config/include/config/state_api_config.hpp
libraries/config/src/chain_config.cpp
libraries/config/src/config.cpp
libraries/config/src/state_api_config.cpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/final_chain_test.cpp
tests/pbft_manager_test.cpp
tests/util_test/util.hpp

https://github.com/Taraxa-project/taraxa-node/issues/1899
https://github.com/Taraxa-project/taraxa-evm/pull/112 should be reviewed and merged first

fix: make DPOS config required

---

libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp

Genesis hash check and network id check is now done before light node check. 
On testnet there was a lot of these light node errors generated because of the nodes running old version but this check was done before the version/hash check.

chore: light node error log cleanup

---

libraries/core_libs/consensus/src/transaction/transaction_queue.cpp

fix: transaction with same nonce

---

tests/full_node_test.cpp

https://github.com/Taraxa-project/taraxa-node/issues/2169

fix: FullNodeTest.sync_five_nodes fails

---

libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/testnet.json

enables GraphQL on devnet and testnet

chore: enables GraphQL on devnet and testnet

---

libraries/cli/include/cli/config_jsons/devnet.json
libraries/cli/include/cli/config_jsons/testnet.json

chore: enables GraphQL on testnet

---

charts/taraxa-node/Chart.yaml

Dependency of mongodb with broken probes 
Bump version of explorer. Which is using latest mongodb chart.
Changed version of explorer helm chart

bump explorer version

---

libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
tests/dag_block_test.cpp
tests/final_chain_test.cpp
tests/pbft_manager_test.cpp
tests/util_test/node_dag_creation_fixture.hpp

Should be reviewed and merged first https://github.com/Taraxa-project/taraxa-evm/pull/116
https://github.com/Taraxa-project/taraxa-evm/issues/113

fix: set account nonce to trx_nonce+1, not trx_nonce. contract address and nonce on contract creation.

---

libraries/core_libs/network/src/tarcap/stats/node_stats.cpp

Update testnet evm

---

libraries/core_libs/consensus/include/final_chain/data.hpp
libraries/core_libs/consensus/src/final_chain/data.cpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/graphql/src/query.cpp
libraries/core_libs/network/graphql/src/ws_server.cpp
libraries/core_libs/network/include/network/ws_server.hpp
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/core_libs/network/rpc/jsonrpc_ws_server.cpp
libraries/core_libs/network/src/ws_server.cpp
libraries/core_libs/node/src/node.cpp

Graphql rpc improvements

---

charts/taraxa-node/Chart.yaml

chore: removes sandbox app

---

.circleci/config.yml

bump orb version

---

.circleci/config.yml
charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/boot-node.yaml
charts/taraxa-node/templates/consensus-node.yaml
charts/taraxa-node/templates/taraxa-node.yaml
charts/taraxa-node/values.yaml

We want to allow to spec persistance (PVC) per node type.
Adds persistance settings (PVC) for each node type
Added persistance to manifests

[helm-chart] - v0.2.4: allow to spec persistance per node type

---

libraries/core_libs/storage/src/storage.cpp

Delete does not always reduce the disk size. Db file compaction ensures that the delete removes the file. Compact is an expensive operation but since light node deletion is only done once a day it should not be a performance issue.
Deleting additional transactions related data from light node for all the transactions that were included in the blocks for which period data is not available.
For any long running network this ensures that disk size of db (not state_db) for light node should reduce by over 80%

chore: compact db after light node delete

---

libraries/config/include/config/genesis.hpp
libraries/config/src/config.cpp
libraries/config/src/genesis.cpp

fix: add method setting blocks_per_year

---

libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
libraries/core_libs/network/src/tarcap/stats/time_period_packets_stats.cpp

chore: additional max stats logging

---

conanfile.py
for_devs/local-net
libraries/CMakeLists.txt
libraries/cli/include/cli/config_jsons/default/default_config.json
libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
libraries/config/include/config/network.hpp
libraries/config/src/network.cpp
libraries/core_libs/CMakeLists.txt
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/node/include/node/node.hpp
libraries/core_libs/node/src/node.cpp
libraries/metrics/CMakeLists.txt
libraries/metrics/include/metrics/metrics_group.hpp
libraries/metrics/include/metrics/metrics_service.hpp
libraries/metrics/include/metrics/network_metrics.hpp
libraries/metrics/include/metrics/pbft_metrics.hpp
libraries/metrics/include/metrics/transaction_queue_metrics.hpp
libraries/metrics/src/metrics_service.cpp

feat: add metrics service. add some basic metrics updaters

---

CMakeLists.txt
docker-entrypoint.sh
libraries/cli/include/cli/config.hpp
libraries/cli/src/config.cpp
programs/taraxa-bootnode/main.cpp

New flag for setting listening port

chore: add support for setting port via flag

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/taraxa-node.yaml
charts/taraxa-node/templates/taraxa-nodes-services-loadbalancer.yaml
charts/taraxa-node/templates/taraxa-nodes-services-nodeport.yaml
charts/taraxa-node/values.yaml

To fix discovery in kubernetised environments.
Added a new `Service` for each rpc-node of type `NodePort`, so discovery protocol can work on the same ips in kuberneties environments.
Added a new `Service` for each rpc-node of type 'NodePort.'

Chore/chart v0.3.1

---

.circleci/config.yml
charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/boot-node-servicemonitor.yaml
charts/taraxa-node/templates/consensus-node-servicemonitor.yaml
charts/taraxa-node/templates/taraxa-node-servicemonitor.yaml
charts/taraxa-node/values.yaml

We want to instrument `taraxa-node` code with Prometheus metrics and expose them.
Added `ServiceMonitor` to helm-chart for prometheus-operator
Added `ServiceMonitor` to helm-chart for prometheus-operator

[helm-chart] - ServiceMonitor for nodes

---

libraries/cli/include/cli/config_jsons/default/default_config.json
libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
libraries/config/include/config/network.hpp
libraries/config/src/config.cpp
libraries/config/src/network.cpp
libraries/core_libs/network/include/network/tarcap/stats/time_period_packets_stats.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
libraries/core_libs/network/src/tarcap/stats/time_period_packets_stats.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/py/config/config1.json
tests/py/config/config2.json
tests/py/config/config3.json
tests/py/config/config4.json
tests/py/config/config5.json
tests/test_util/config/config0.json
tests/test_util/src/test_util.cpp

Issue 2244/peer ddos protection

---

tests/full_node_test.cpp

When pruning state db, if block over proposal period were pruned, transaction estimation was not done correctly.
Changed the test to prune only block below proposal period

fix: prune unit test

---

libraries/common/include/common/util.hpp
libraries/core_libs/consensus/include/dag/dag_manager.hpp
libraries/core_libs/consensus/include/pbft/pbft_chain.hpp
libraries/core_libs/consensus/src/dag/dag_manager.cpp
libraries/core_libs/consensus/src/pbft/pbft_chain.cpp

Replace boost locks by std locks
boost locks in vote manager are replaced in this PR
https://github.com/Taraxa-project/taraxa-node/pull/2273

chore: remove boost locks from codebase

---

libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
tests/network_test.cpp

chore: fix enable update peer chainsize test

---

libraries/core_libs/consensus/include/dag/dag_manager.hpp
libraries/core_libs/consensus/src/dag/dag_manager.cpp
libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
libraries/metrics/CMakeLists.txt
tests/dag_test.cpp
tests/full_node_test.cpp
tests/network_test.cpp
tests/pbft_manager_test.cpp
tests/test_util/include/test_util/samples.hpp
tests/test_util/src/node_dag_creation_fixture.cpp
tests/test_util/src/samples.cpp

https://github.com/Taraxa-project/taraxa-node/issues/1244

feat: do not save genesis block in dag blocks in database

---

libraries/cli/include/cli/config_jsons/devnet/devnet_config.json

chore: disable ddos protection

---

libraries/cli/include/cli/config_jsons/default/default_config.json
libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
libraries/config/include/config/network.hpp
libraries/config/src/config.cpp
libraries/config/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
libraries/core_libs/network/src/tarcap/shared_states/peers_state.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
tests/py/config/config1.json
tests/py/config/config2.json
tests/py/config/config3.json
tests/py/config/config4.json
tests/py/config/config5.json
tests/tarcap_threadpool_test.cpp
tests/test_util/config/config0.json

Issue 2299/ddos protection

---

libraries/core_libs/consensus/src/final_chain/final_chain.cpp

Fixes https://github.com/Taraxa-project/taraxa-node/issues/2302

chore: use correct period for calculating rewards

---

libraries/cli/include/cli/config_jsons/devnet/devnet_config.json

chore: fix devnet config

---

libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json

chore: set default delegation for our validators to 100k

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/boot-node.yaml
charts/taraxa-node/templates/consensus-node.yaml
charts/taraxa-node/templates/taraxa-node.yaml

Fix key: `image.imagePullPolicy` -> `image.pullPolicy`

[helm-chart] - fix: imagePullPolicy -> pullPolicy

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/values.yaml

chore: adds cors config for indexer

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/taraxa-node.yaml

- added changelog entries
- changed db_path to data_dir

Chore: helm-chart v0.2.8

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/taraxa-node.yaml

- changed db_path to data_dir
- bump chart version
- updated changelog for helm-chart

Chore: helm-chart v0.3.5

---

libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_votes_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp

The problem was that if just 1 of votes from all sync votes was already processed/validated before, we would drop all other votes

Issue 2372/fix votes syncing

---

libraries/core_libs/consensus/src/final_chain/final_chain.cpp

Prune of state_db can take up to few minutes depending on the size of the database. It is run on separate thread not to block pbft progress on the node.

chore: asynchronous prune of state_db

---

CMakeLists.txt

increase net version

---

libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp

Ignore one vote but process others if one vote already validated

Reward votes sync fix

---

libraries/cli/include/cli/config_jsons/testnet/testnet_config.json

remove rpc nodes

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/secrets.yaml
charts/taraxa-node/templates/transaction-generation-script.yaml
charts/taraxa-node/templates/transaction.generation.statefulset.yaml
charts/taraxa-node/values.yaml

chore: adds transaction generating script

---

charts/taraxa-node/CHANGELOG.md
charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/taraxa-node-servicemonitor.yaml
charts/taraxa-node/values.yaml

We need to scrape prometheus metrics from taraxa-indexer
Added metrics port.
Added metrics port.

[helm-chart] Scrape metrics from taraxa-indexer

---

libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json

change initial_validator keys

---

tests/network_test.cpp

Fix network test

---

libraries/cli/include/cli/config.hpp
libraries/cli/src/config.cpp
libraries/config/include/config/config.hpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/include/storage/migration/migration_base.hpp
libraries/core_libs/storage/include/storage/migration/migration_manager.hpp
libraries/core_libs/storage/include/storage/migration/transaction_hashes.hpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/migration/migration_manager.cpp
libraries/core_libs/storage/src/migration/transaction_hashes.cpp
libraries/core_libs/storage/src/storage.cpp

1. Add migration functionality including base class for migrations and migration manager that will apply registered migrations. 
2. Add migration for transactions hashes

Migrations

---

libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp

Set reward votes period and round from 2t+1 votes

Reward votes initialization

---

libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/migration/period_data.cpp
libraries/core_libs/storage/src/storage.cpp

copy colu,mn before aplying migration

---

libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/status_packet_handler.cpp
libraries/core_libs/node/include/node/node.hpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/src/storage.cpp
tests/network_test.cpp
tests/p2p_test.cpp

- Removed "ifs" from code that was there only due to tests
- tests code cleanup

clean up code from test related code

---

CMakeModules/cpp_graphql_gen.cmake
libraries/core_libs/CMakeLists.txt
libraries/core_libs/network/graphql/include/graphql/block.hpp
libraries/core_libs/network/graphql/include/graphql/query.hpp
libraries/core_libs/network/graphql/include/graphql/transaction.hpp
libraries/core_libs/network/graphql/include/graphql/types/dag_block.hpp
libraries/core_libs/network/graphql/schema/schema.taraxa.graphql
libraries/core_libs/network/graphql/src/block.cpp
libraries/core_libs/network/graphql/src/query.cpp
libraries/core_libs/network/graphql/src/transaction.cpp
libraries/core_libs/network/graphql/src/types/dag_block.cpp

Add pbft block hash to pbft block object in graphql. So after this change it will be possible to show it in the explorer and search for blocks there

feat: add pbftHash to graphql pbft block

---

libraries/config/include/config/config.hpp
libraries/config/src/config.cpp
libraries/core_libs/node/src/node.cpp
libraries/logger/src/logger_config.cpp

Add a thread that is checking config file modification date and reloading logging config in case of change

feat: check for config change and update logging config on change

---

libraries/core_libs/storage/src/storage.cpp

Using getPeriodTransactions to get transactions hashes for a period is slow because it requires deserializing all transactions and calculating hash. This was causing huge delay on each call to DbStorage::clearPeriodDataHistory
Getting transactions hashes from dag blocks is much faster and keeps clearPeriodDataHistory under one second to execute.

chore: improve light node history delete

---

libraries/config/include/config/config.hpp
libraries/config/include/config/genesis.hpp
libraries/config/include/config/hardfork.hpp
libraries/config/include/config/state_config.hpp
libraries/config/src/config.cpp
libraries/config/src/genesis.cpp
libraries/config/src/hardfork.cpp
libraries/core_libs/consensus/include/rewards/rewards_stats.hpp
libraries/core_libs/consensus/include/slashing_manager/slashing_manager.hpp
libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
libraries/core_libs/consensus/src/rewards/rewards_stats.cpp
libraries/core_libs/consensus/src/slashing_manager/slashing_manager.cpp
libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/common/ext_votes_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/get_next_votes_bundle_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/vote_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/votes_bundle_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/v1/init_packets_handlers.hpp
libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/common/ext_votes_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_next_votes_bundle_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/vote_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/votes_bundle_packet_handler.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
libraries/core_libs/node/src/node.cpp
tests/rewards_stats_test.cpp
tests/state_api_test.cpp

slashing manager

---

libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json

Test magnolia hf on devnet on block 1230000

chore: enable test for magnolia hf on devnet

---

CMakeLists.txt
CMakeModules/cpp_graphql_gen.cmake
libraries/core_libs/CMakeLists.txt
libraries/core_libs/network/graphql/include/graphql/block.hpp
libraries/core_libs/network/graphql/include/graphql/query.hpp
libraries/core_libs/network/graphql/include/graphql/transaction.hpp
libraries/core_libs/network/graphql/include/graphql/types/dag_block.hpp
libraries/core_libs/network/graphql/schema/schema.taraxa.graphql
libraries/core_libs/network/graphql/src/block.cpp
libraries/core_libs/network/graphql/src/query.cpp
libraries/core_libs/network/graphql/src/transaction.cpp
libraries/core_libs/network/graphql/src/types/dag_block.cpp
libraries/core_libs/network/include/network/http_server.hpp
libraries/core_libs/network/src/http_server.cpp

Fix crash on graphql

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/include/final_chain/state_api_data.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/final_chain/state_api_data.cpp
libraries/core_libs/network/rpc/Debug.cpp
libraries/core_libs/network/rpc/Debug.h
libraries/core_libs/network/rpc/Debug.jsonrpc.json
libraries/core_libs/network/rpc/DebugClient.h
libraries/core_libs/network/rpc/DebugFace.h

Add method to get validator stakes in one request to speed up indexer syncing

Get validators stakes

---

CMakeLists.txt
libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json

Version v1.5.1

---

CMakeModules/rocksdb.cmake

fix building

---

libraries/cli/include/cli/config_jsons/default/default_genesis.json
libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
libraries/config/include/config/hardfork.hpp
libraries/config/src/hardfork.cpp
tests/test_util/src/test_util.cpp

divide aspen hardfork into 2 parts

---

libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp

When getting reward votes for the last pbft block to be synced it is possible that in the meantime another block was pushed in the chain. This causes a malicious peer exception on the other end since reward votes do not match the period that is being sent.
This is fixed by simply sending just the block which will force the other side to ask for more blocks.

fix: pbft sync rewards period mismatch

---

libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json

set timestamp to Friday 22. December 2023 11:00:00 GMT

---

libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/node/src/node.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
tests/transaction_test.cpp

Revert dag save optimization

---

CMakeLists.txt
libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json

set release 1.6.0 config for testnet

---

libraries/common/include/common/encoding_rlp.hpp
libraries/core_libs/consensus/include/pillar_chain/bls_signature.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_block.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
libraries/core_libs/consensus/src/pillar_chain/bls_signature.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_block.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
tests/full_node_test.cpp

Issue 2622/optimize stakes changes processing

---

libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json

change hardforks block nums

---

libraries/config/include/config/hardfork.hpp
libraries/core_libs/consensus/include/rewards/block_stats.hpp
libraries/core_libs/consensus/src/rewards/block_stats.cpp
libraries/core_libs/consensus/src/rewards/rewards_stats.cpp
libraries/core_libs/node/src/node.cpp
tests/rewards_stats_test.cpp

Change dag rewards to reward only dag blocks within pbft block that has the minimum difficulty within the pbft block

chore: dag rewards

---

libraries/config/include/config/hardfork.hpp
libraries/config/src/hardfork.cpp
libraries/core_libs/consensus/include/pillar_chain/pillar_block.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
libraries/core_libs/consensus/include/pillar_chain/signatures.hpp
libraries/core_libs/consensus/src/pillar_chain/pillar_block.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/consensus/src/pillar_chain/signatures.cpp
libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/include/network/tarcap/packet_types.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/get_pillar_chain_sync_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/pillar_chain_sync_packet_handler.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pillar_chain_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/pillar_chain_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
libraries/core_libs/network/src/threadpool/priority_queue.cpp
libraries/core_libs/node/src/node.cpp

add pillar chain syncing

---

libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json

remove aspen hf part2 block num from config

---

docker-entrypoint.sh

chore: adds automatic external ip detection

---

libraries/cli/include/cli/config_jsons/default/default_genesis.json
libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
libraries/config/src/hardfork.cpp
libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
libraries/core_libs/node/src/node.cpp
libraries/types/pbft_block/include/pbft/pbft_block.hpp
libraries/types/pbft_block/src/pbft_block.cpp
libraries/types/vote/include/vote/vote.hpp
libraries/types/vote/src/pbft_vote.cpp
libraries/types/vote/src/pillar_vote.cpp
libraries/types/vote/src/vote.cpp
tests/full_node_test.cpp

anchor pillar block hash into the pbft block

---

libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json

update testnet. set timestamp to Thursday 15. February 2024 15:00

---

libraries/core_libs/network/rpc/eth/LogFilter.cpp
tests/rewards_stats_test.cpp

fix: LogFilter topic filtering without address specified

---

libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
tests/full_node_test.cpp

save current pillar block and stakes into db

---

libraries/config/include/config/hardfork.hpp
libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/network/include/network/network.hpp
libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/pbft_sync_packet_handler.cpp

sync pillar votes after restart

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/network/rpc/Debug.cpp
libraries/core_libs/network/rpc/Debug.h
libraries/core_libs/network/rpc/Debug.jsonrpc.json
libraries/core_libs/network/rpc/DebugClient.h
libraries/core_libs/network/rpc/DebugFace.h

Related evm PR https://github.com/Taraxa-project/taraxa-evm/pull/229

feat: add debug_dposTotalAmountDelegated method to the API

---

doc/RPC.md
libraries/common/include/common/encoding_solidity.hpp
libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/include/final_chain/state_api_data.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_block.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/final_chain/state_api_data.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_block.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/network/include/network/ws_server.hpp
libraries/core_libs/network/rpc/jsonrpc_ws_server.cpp
libraries/core_libs/network/src/ws_server.cpp
libraries/core_libs/storage/include/storage/storage.hpp
libraries/core_libs/storage/src/storage.cpp
tests/pillar_chain_test.cpp

change stakes changes in pillar block to vote counts

---

doc/RPC.md
libraries/core_libs/consensus/include/pillar_chain/pillar_block.hpp
libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
libraries/core_libs/consensus/src/pillar_chain/pillar_block.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
libraries/core_libs/network/include/network/ws_server.hpp
libraries/core_libs/network/rpc/Taraxa.cpp
libraries/core_libs/network/rpc/Taraxa.h
libraries/core_libs/network/rpc/Taraxa.jsonrpc.json
libraries/core_libs/network/rpc/TaraxaClient.h
libraries/core_libs/network/rpc/TaraxaFace.h
libraries/core_libs/network/rpc/jsonrpc_ws_server.cpp
libraries/core_libs/network/src/ws_server.cpp
libraries/core_libs/node/src/node.cpp
libraries/types/vote/include/vote/pillar_vote.hpp
libraries/types/vote/src/pillar_vote.cpp
tests/pillar_chain_test.cpp

Rework pillar blocks subscription

---

CMakeLists.txt
libraries/core_libs/consensus/src/transaction/transaction_queue.cpp

Fix loop in transaction queue purge which might loop indefinitely

fix: purge loop

---

CMakeLists.txt
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/pillar_votes_bundle_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pillar_votes_bundle_packet_handler.cpp

bugfix: split pillar vote packet to serverl ones

---

CMakeLists.txt
libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/pillar_votes_bundle_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pillar_votes_bundle_packet_handler.cpp

chore: increase version and add cornus_hf block to testnet genesis

---

libraries/core_libs/network/rpc/Debug.cpp

EVM PR that should be reviewed first. 
https://github.com/Taraxa-project/taraxa-evm/pull/249

fix: tracing execution block number

---

libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/common/ext_votes_packet_handler.hpp
libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/dag_block_packet_handler.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/dag_block_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp

- added move semantics to some of the packet constructors
- fixed double sending of transactions in dag block packet

fix dag block packet double sending of txs, optimize packets ctors

---

libraries/core_libs/network/include/network/tarcap/packets/latest/transaction_packet.hpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp

fix transaction packet

---

CMakeLists.txt

Update version to 1.12.1

---

libraries/cli/include/cli/config_jsons/default/default_genesis.json
libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
libraries/config/include/config/hardfork.hpp
libraries/config/src/hardfork.cpp
libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
tests/rewards_stats_test.cpp

Added to cornus hardfork:
- change of delegation locking period
EVM PR:
https://github.com/Taraxa-project/taraxa-evm/pull/257

Delegation locking period change

---

libraries/core_libs/network/src/network.cpp
libraries/core_libs/network/src/tarcap/taraxa_capability.cpp

fix multiple tarcaps

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp

Handle correctly transactions which are included in multiple dag blocks but did not increase nonce in EVM due to no balance

fix: handle transactions with no nonce increase

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

do not require full block data before soft voting

---

doc/RPC.md

chore: add eth_subscribe to the RPC doc

---

CMakeLists.txt

increase version

---

libraries/core_libs/network/include/network/tarcap/packet_types.hpp

move pbft sync packets to high priority queue

---

CMakeLists.txt
libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp

Limit trx pool size by data limit.
Enfore transaction packet size limit.

chore: limit trx pool by data size

---

libraries/core_libs/consensus/src/dag/dag_manager.cpp

fix: light node db pruning

---

libraries/cli/src/config.cpp

fix port parsing

---

libraries/config/include/config/config.hpp

Reduce light node history to one day

chore: reduce light node history

---

libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
libraries/config/include/config/network.hpp
libraries/config/src/network.cpp
libraries/core_libs/network/include/network/http_server.hpp
libraries/core_libs/network/include/network/ws_server.hpp
libraries/core_libs/network/src/http_server.cpp
libraries/core_libs/network/src/ws_server.cpp
libraries/core_libs/node/src/node.cpp

Revert rate limit

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

improve pillar block error msg

---

CMakeLists.txt
libraries/core_libs/consensus/src/transaction/transaction_manager.cpp

fix: out of gas trx

---

libraries/core_libs/network/rpc/Test.cpp
libraries/core_libs/network/rpc/eth/Eth.cpp
libraries/types/transaction/src/transaction.cpp
tests/final_chain_test.cpp
tests/rpc_test.cpp

feat: add chainId to trx json

---

libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp

added missing throw

---

libraries/core_libs/consensus/include/final_chain/final_chain.hpp
libraries/core_libs/consensus/include/final_chain/state_api.hpp
libraries/core_libs/consensus/src/final_chain/final_chain.cpp
libraries/core_libs/consensus/src/final_chain/state_api.cpp
libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
tests/final_chain_test.cpp

evm pr:
https://github.com/Taraxa-project/taraxa-evm/pull/271

fix vote counts for jailed validators

---

libraries/core_libs/consensus/src/pbft/pbft_manager.cpp

fix eligible wallets assert

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/bootnode-servicemonitor.yaml
charts/taraxa-node/templates/consensus-node-servicemonitor.yaml
charts/taraxa-node/templates/taraxa-node-servicemonitor.yaml
charts/taraxa-node/values.yaml

enable metric releballings

---

charts/taraxa-node/Chart.yaml
charts/taraxa-node/templates/taraxa-node-statefulset.yaml
charts/taraxa-node/values.yaml

added resources to indexer container
