Taraxa-project/taraxa-node

- src/chain/chain_config.cpp
- src/consensus/pbft_chain.cpp
- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/consensus/vote.cpp
- src/consensus/vote.hpp
- src/network/network.cpp
- src/network/network.hpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- src/node/full_node.cpp
- src/node/full_node.hpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/p2p_test.cpp
Fix PBFT next voting 2 values in the same step issue
* Implement next votes for previous PBFT round class and integrate with PBFT manager
* Implement next votes read/write in DB APIs and add unit tests
* Implement next votes syncing. Not only sync when node is behind to peer PBFT round,  but also will sync when node has a short next votes size in previous PBFT round
* Process synced next votes. If node is behind to peer, push synced next votes into unverified queue. If node has same PBFT round with peer but has a short previous next votes size, verify the votes and update own previous next votes structure
* Add next votes bundle syncing unit tests
> Fix PBFT next voting 2 values in the same step issue

- Dockerfile
- Jenkinsfile
Remove ctest from docker build
Add new image build for ctest
Add steps to run the ctest on Jenkins instead of docker build
Add artifacts to jenkins on failure
Run ctest separated from docker build so we can capture coredums.
I am trying to get the temp folder, this also seems to contain the databases and some other files, for now, I don't know how big they will be, if they are too big, we may not able to get everything.
Does this folder help in figuring out the problem? If not I can get the coredump only.
ps: The new image build should be cached so not much time added
> Separate tests from build

- src/common/static_init.hpp
The docker container doesn't stop when sending sigkill via CRTL+C
> fix(init): wrong signal for sigkill

- docker-entrypoint.sh
Hack to get coredumps when running on GKE to persistent storage.
Right now I am letting it enabled as default, but I am ok with changing it and only enable in some deploys.
(not tested on actual gke)
> Enable hack to copy coredumps on gke

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
Add a simple summary of node status in a SUMMARY log channel:
```
SUMMARY [2021-05-13 00:13:53.034257] INFO: Connected to 2 peers
SUMMARY [2021-05-13 00:13:53.034516] INFO: In sync since launch for 100% of the time
SUMMARY [2021-05-13 00:13:53.034658] INFO: Queued unverified transaction: 0
SUMMARY [2021-05-13 00:13:53.034788] INFO: Queued verified transaction:   0
SUMMARY [2021-05-13 00:13:53.034917] INFO: Max DAG block level in DAG:    1
SUMMARY [2021-05-13 00:13:53.035049] INFO: Max DAG block level in queue:  0
SUMMARY [2021-05-13 00:13:53.035188] INFO: PBFT chain size:               1
SUMMARY [2021-05-13 00:13:53.035271] INFO: Current PBFT round:            5
SUMMARY [2021-05-13 00:13:53.035353] INFO: DPOS total votes count:        1
SUMMARY [2021-05-13 00:13:53.035434] INFO: PBFT …
```
> feature: node status SUMMARY log channel

- src/network/taraxa_capability.cpp
Currently summary log prints something like this:
```
2021-05-14 16:47:11.150796 SUMMARY INFO Syncing for 1.2e+02 seconds, 12% synced
```
this should improve readability
> better printing of seconds in summary log

- src/network/taraxa_capability.cpp
The current logic for checking if a pbft block + certs that is sent over the network is valid doesn't seem to hold up.
Fixes #759 
_I tested it against the devnet as follows and syncing is continuous without stopping..._
```
docker login -u _token -p "$(gcloud auth print-access-token)" https://gcr.io
docker pull gcr.io/jovial-meridian-249123/taraxa-node:pr-769-build-1
docker run --rm --name taraxa-devnet gcr.io/jovial-meridian-249123/taraxa-node:pr-761-build-1 join devnet
```
> fix(syncing): refactor error checking for pbft block syncing

- src/consensus/vote.cpp
- src/network/taraxa_capability.cpp
Remove votes more than a round head from the unverified queue, if they fail validation, to prevent excessive unvalidated vote buildup.
Fixes #742 
In getVerifiedVotes we try to validate unverified votes, and if they fail we remove them now from unverified queue if they are more than one round ahead.
If we are boostrapping to the correct future round, and have synced to the latest full chain then votes will pass validation.   
If they are only a round ahead they may pass validation as soon as we catch up with our asynchronous execution.
> fix(vote): remove votes more than a round ahead from the unverified queue

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/consensus/vote.cpp
- src/consensus/vote.hpp
- src/storage/db_storage.hpp
- tests/crypto_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/vote_test.cpp
Since cannot guarantee all nodes have same size of PBFT chain when they vote, remove last PBFT block hash for vote VRF sortition 
https://github.com/Taraxa-project/taraxa-node/issues/780
> bugfix(vote): Remove last PBFT block hash for vote VRF sortition

- .gitmodules
Make taraxa submodules paths relative. After that change on submodules initialization it will make a url from that one you used for the main repo saving a scheme. So if you clones a repo with `ssh` it will be also used for all submodules
> chore(gitmodules): change taraxa submodule paths to relative

- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- tests/p2p_test.cpp
- disable discovery for some test, so external nodes can not interfere
- send test msg with big buffer (15MB)
> test(p2p): test sending test msgs with 15MB payload

- .circleci/config.yml
This is a fix to change the prefix on the image name to be pushed to dockerhub.
> Added taraxa prefix for pushes to dockerhub on master branch builds

- src/dag/dag_block_manager.hpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- src/node/full_node.cpp
- add missing lock
- change when we mark that peer is active
What I have noticed, is that sometimes e.g. right now on testnet peer is trying to send my node a lot of missing DAG blocks (10k),
so peer splits those to multiple packets, but it takes while to process it. Meanwhile he is trying to send me status back, but is somewhere deep down in send/write queue and it will not be send in time. Then  we disconnect each other, because we did not get status packet.
One of the solutions is mark all incoming packet as some kind of activity between us, so we do not disconnect
> fix(networking): redefine where we mark peer as active & missing lock

- config/_template.json
After #824  to address #822  we didn't change the default verbosity in the template to ERROR as suggested by @MatusKysel.  Now we have way to many INFO logs enabled by default!
#822 has the suggestion that we didn't fully carry through on.
Changes default logging verbosity level to ERROR
> fix(logging): change default log verbosity level to ERROR

- src/consensus/block_proposer.cpp
- src/dag/dag_block.cpp
- src/dag/dag_block_manager.cpp
- src/dag/vdf_sortition.cpp
- src/dag/vdf_sortition.hpp
- tests/crypto_test.cpp
- tests/dag_block_test.cpp
- tests/network_test.cpp
Removed VDF logs, that were created for each instance of vdfsortition and we used it only in case of invalid VDF or VRF
> perf(vdf): remove logging vdfsortition class

- src/consensus/pbft_manager.cpp
- src/network/taraxa_capability.cpp
All boot nodes will crash at testnet, due to out of memory.
There are too many next votes bundle syncing 
1. Change to next votes bundle syncing every 100 steps at PBFT
2. Only send next votes bundle to peers who are behind the current PBFT round
> fix(next votes): Improve next votes bundle syncing

- tests/network_test.cpp
- tests/util_test/util.hpp
- tests/vote_test.cpp
In CircleCI build, there are unit tests failed intermittently at Mac machine, works in Linux machine. And cannot reproduce in local.
So far, all of the intermittently failed unit tests are related to count object(tansactions, votes, blocks) number. I doubt there is an race condition may fail at here:
https://github.com/Taraxa-project/taraxa-node/blob/develop/src/network/taraxa_capability.cpp#L213
1. Remove minimum peers connection, since no one use that
2. Add waiting nodes initial status packets passed when launch nodes
3. Fix and improve network/vote unit tests
> chore(unit test): Add waiting nodes initial status packets passed and fix unit tests

- .circleci/config.yml
Fix circleci stopping the process before the helm test/install has time to fail.
Also, decrease the timeout for the helm commands as they were too long for the current usage.
> Increase circleci no_output_timeout and decrease helm install/test timeout

- .github/workflows/trigger-ci-on-branch.yml
Fixes trigger for testnet branch with valid branch name.
Right now it's calling the circleci action with `refs/heads/testnet`
This change calls the action just with the branch name
> chore(ci) fixes trigger for testnet branch with valid branch name

- src/network/taraxa_capability.cpp
Prevent gossiping new blocks while syncing
While node is syncing, OnBlockVerified was called for each of the old DAG block that was verified. This was gossiped to all other nodes as if it is a completely new block. This is now prevented.
> fix: prevent gossiping new blocks while syncing

- .github/actions/prnet/action.yml
- .github/workflows/pr-actions.yml
- .github/workflows/pr-net-cleanup-on-close.yml
This pull request contains the github actions to trigger circleci jobs to deploy / redeploy / cleanup pr-nets
This pr just contains the github actions, but not the circleci config
> Added github actions to trigger circleci deploy pr-nets

- CMakeModules/clang_tidy.cmake
clang-tidy is not properly configured and used at the moment. No need to require it until we properly set it up to be used during building ALL...
> chore(cmake): make clang-tidy optional as it is not used at the moment

- src/node/full_node.cpp
- src/node/full_node.hpp
- src/transaction_manager/transaction.cpp
- src/transaction_manager/transaction.hpp
- src/util/util.hpp
- tests/transaction_test.cpp
1) Fixed a bug in transaction rlp parsing. We used to require v, r, s signature fields to be full-sized, but actually it's okay by the standard for them to be not full-sized due to leading zeroes trimming.
2) Simplified and cleaned up the code in some places
3) Fixed inconsistent formatting by running clang-format
4)  fixed failure to deduce weak_ptr constructor template arguments on some macos compilers
> Followup on PR #843

- src/network/taraxa_capability.cpp
- src/node/full_node.hpp
- tests/network_test.cpp
- tests/util_test/samples.hpp
Splitting PbftBlockPacket if over max size of 15MB
PbftBlockPacket which can contain multiple pbft packets together with the dag blocks and transactions was previously only split by pbft packets meaning that any pbft block packet over 15MB could not be split. With the changes in this PR splitting is done on the dag block level. This still means that no DAG block over 15MB can be sent.
Changes in taraxa capability on sending and processing PBFT packet. Format is changed for any packet with pbft and dag blocks changing order in the packet. Pbft block is only sent once all dag blocks are sent
Unit test added which tests syncing of large pbft block
> Splitting PbftBlockPacket if over max size of 15MB

- .circleci/config.yml
This PR is to speedup docker image builds via implementing external cache method.
i have performed may tests, trying to cover most of the variants that i was able to reproduce.
it costs about 10' downloading two cache images, one for current branch and one to be the latest, but overall i think it lowers the built time at least to half.
i have discovered that cacheable layers are all on the actual ctest image, since the taraxad image gets most of the stuff removed, so i retag ctest image to be the caching image.
> implemented external caching with cci-x/docker-registry-image-cache

- .circleci/config.yml
Some connan packages are showing errors when trying to get installed, cache could be corrupted so changing them to a new version
only cache keys were changed.
> chore(circleci): Change Conan cache keys to fix a corruption

- tests/network_test.cpp
network_test core dumped for me locally
> chore(tests): check for nullptr in sync_large_pbft_block test

- src/network/taraxa_capability.cpp
- src/node/full_node.hpp
optimize syncing non finalized dag blocks
Sending hashes with the getBlocksPacket to only retrieve non finalized blocks not yet known by the requesting node
> optimize syncing non finalized dag blocks

- src/dag/dag.cpp
- src/dag/dag.hpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
In case we receive corrupted RLP let's not log content of that RLP as it can cause crash of whole app
> fix(RLP): do not log corrupted RLP as it can cause crash

- src/dag/dag_block_manager.cpp
- src/dag/dag_block_manager.hpp
- src/node/full_node.cpp
When DAG block is missing a tip or pivot there was a state in which we got in an endless loop maxing out CPU on checking the same block over and over again. Now the check is only done when we receive another block with smaller level
> fix: optimize block queue processing

- src/network/taraxa_capability.cpp
I would also include this check
> chore(dag_sync): check if DAG is not nullptr

- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- tests/util_test/util.hpp
Transactions that are sent on short intervals might get sent to the node before the status message. This will cause the node to ignore the packet and transactions but at the same time transactions would incorrectly be marked as known. The fix ensures status message is sent before sending the transactions
> fix: ensure status message is sent first

- src/dag/dag.cpp
- src/dag/dag.hpp
- src/network/taraxa_capability.cpp
Non finalized blocks were retrieved with reference which means is was accessed without any lock protection. Returning a copy instead
> fix: protect non finalized block map

- src/consensus/vote.cpp
- src/consensus/vote.hpp
- src/network/taraxa_capability.cpp
Optimized RLP votes processing.
Removed verify method in VrfPbftSortition which actually did not do anything since there was no check for return value.
These changes significantly reduce time of processing vote packets
> fix: optimize vote processing

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
Currently we had a fatal flaw in doing this based on round. But in certain circumstances we could violate ability to make consensus for next voting if partitioning of the count of rounds have been waiting occurred. Now we do it based on time, so that after some point in time > 2t+1 nodes will have timed-out.
> fix(pbft): refactor the way we opt to give up on non-received next voted pbft block

- src/consensus/block_proposer.cpp
Block proposer thread would get into CPU intensive loop without any sleep when node syncing
> fix: CPU intensive loop when syncing in block proposer

- src/network/network.cpp
- src/network/network.hpp
- src/network/rpc/Test.cpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
Useful for the status app and for cleaning up SILENT logging to not include node status.
> feature: improve rpc node status and summary info logging

- src/network/taraxa_capability.cpp
Deadlock was happening in this order:
we executed `checkLiveness()` if condition was met we went for disconnect here https://github.com/Taraxa-project/taraxa-node/blob/develop/src/network/taraxa_capability.cpp#L1418 
which will call `onDisconnect()` and then -> `erasePeer()`
in `checkLiveness` we are creating shared_lock https://github.com/Taraxa-project/taraxa-node/blob/develop/src/network/taraxa_capability.cpp#L1412 and then later in `erasePeer` we are creating uniqe_lock https://github.com/Taraxa-project/taraxa-node/blob/develop/src/network/taraxa_capability.cpp#L84 
so in this order it will cause deadlock
> fix(peer): remove deadlock

- tests/network_test.cpp
Added sleep fixes the issue during destruction that caused a crash
Have commits from https://github.com/Taraxa-project/taraxa-node/pull/1046 and https://github.com/Taraxa-project/taraxa-node/pull/1048. Them would be removed after merging
> chore(tests): fix network_test/sync_large_pbft_block

- src/network/rpc/RpcServer.cpp
- src/network/rpc/WSServer.cpp
Added calls of `io_context.stop()` fixed numerous async_accept error logs
> chore(tests): fix async_accept error

- src/consensus/vote.cpp
- tests/pbft_manager_test.cpp
Logic before the fix was waiting for vote that wasn't detected by check in the tests for the most of a time. So changed a check to a one that detects it right after the first needed one
> chore(tests): fix tests that was waiting next_vote_type votes

- src/consensus/pbft_manager.cpp
Introduced a consensus error where could give up on previously cert voted (but not pushed) value in giveUpNextVotedBlock_()
> fix(pbft): make sure don't give up a cert voted value

- tests/pbft_chain_test.cpp
Because of not full data that was written to a db we get errors when node starting a `run` that we actually don't need
> chore(tests): fix fix_pbft_chain/pbft_db_test

- src/consensus/pbft_manager.cpp
- src/dag/dag.cpp
- src/dag/dag.hpp
- src/dag/dag_block_manager.cpp
- src/dag/dag_block_manager.hpp
- src/network/taraxa_capability.cpp
- src/node/full_node.cpp
- src/node/full_node.hpp
- tests/dag_test.cpp
We already have internal cache for DAG blocks, but we do not use it and get them all the time from DB. With this approach we use it as much as possible
> perf(dag): use interal dag block cache instead of db

- src/final_chain/final_chain.cpp
- src/util/thread_pool.cpp
- src/util/thread_pool.hpp
1. Remove unnecessary mutex from thread_pool and it locks
2. Remove `executor_` field from `FinalChain` and replace it with direct `executor_thread_.post`. We don't need `strand` here and executor implementation caused some side-effects that caused tests failing
> Rework final chain executor

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
PBFT failed assertion
Debug on consensus node3:
Round 79176, pushed PBFT block #2f2977bf with period 73717 into chain
At the time, last_cert_voted_value_ is NULL_BLOCK_HASH
Round 79177, propose #428f3182, soft vote at #804aa5cb, cannot cert vote because DAG not synced yet
Round 79178, propose #428f3182, soft vote at #c2e7b300, synced block #804aa5cb but cannot push into chain because DAG not synced yet
Round 79179, propose #428f3182, soft vote at #428f3182, cert vote at #428f3182. DAG synced for #804aa5cb, want to push #804aa5cb into chain. But last cert voted value (#428f3182) != the block (#804aa5cb) going to push into chain. Assertion failed.
The special situation shows us that we cannot guaranty last cert voted value must equal to the block is going to push into chain. Should remove …
> fix(pbft): last cert voted value doesn't alway equal to the block is going to push into chain

- CMakeLists.txt
- src/consensus/pbft_chain.cpp
- src/consensus/pbft_chain.hpp
- src/consensus/pbft_manager.cpp
- src/dag/dag.cpp
- src/dag/dag_block_manager.cpp
- src/dag/dag_block_manager.hpp
- src/final_chain/final_chain.cpp
- src/final_chain/final_chain.hpp
- src/network/rpc/Taraxa.cpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- src/network/taraxa_peer.hpp
- src/node/full_node.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- src/taraxad/taraxad_version.hpp
- src/transaction_manager/transaction_manager.cpp
- src/transaction_manager/transaction_status.hpp
- tests/final_chain_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
- tests/transaction_test.cpp
- tests/util_test/util.hpp
For an executed pbft block, cert votes, dag blocks and transactions are now stored as a single block data which improves syncing performance.
> Optimize storing blocks to improve syncing

- src/consensus/pbft_manager.cpp
- src/dag/dag_block_manager.cpp
- src/dag/dag_block_manager.hpp
- src/network/network.cpp
- src/network/network.hpp
- src/network/taraxa_capability.cpp
- src/network/taraxa_capability.hpp
- src/node/full_node.cpp
- tests/dag_block_test.cpp
- tests/pbft_chain_test.cpp
Fixed a bug that dag_syncing state would be left incorrectly to true if an empty BlocksPacket was not sent back
Enable gossip of any proposed block even if in syncing state. 
Enable gossip any block if not in pbft syncing state
Prevent gossip of pbft blocks that are missing dag anchor
> Fix for syncing state

- src/network/taraxa_capability.cpp
requestblocks would go into endless loop of requesting 0 blocks and retrieving 0 blocks
> fix: requestblocks endless loop fix

- src/consensus/pbft_chain.cpp
- src/storage/db_storage.cpp
```
taraxa-node/src/consensus/pbft_chain.cpp:119:20: error: loop variable 'dag_block_rlp' binds to a temporary value produced by a range of type 'dev::RLP' [-Werror,-Wrange-loop-bind-reference]
for (auto const& dag_block_rlp : *it++) {
^
taraxa-node/src/consensus/pbft_chain.cpp:119:8: note: use non-reference type 'dev::RLP'
for (auto const& dag_block_rlp : *it++) {
```
> chore(build): fix build on macOS by using rlp by value

- tests/p2p_test.cpp
- tests/util_test/util.hpp
I have used this test to test `is_boot_node`flag and I would keep it for now, as it improves performance of discovery
> chore(p2p_discover): improve p2p discovery test

- src/transaction_manager/transaction.cpp
We had bug (race condition) in getHash() function:  tx hash is cached during first call to the getHash() and after that  this cached value is returned. To see if we already cached it or not, flag is used but we set this flag before we actually assigned cached value itself.  
> fix(transaction): fix invalid lock guard in getHash()

- CMakeLists.txt
- src/network/rpc/Test.cpp
After minor changes in cmake files bigger part of the project was rebuild without a need in that. So many time was wasting on that rebuilds. 
Because removed variables was needed only it Test part of Network I just removed it. But it could be also added to needed target with `target_compile_definitions` if it is needed
> build: get rid of recompilation bigger part of project after cmake run

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/node/full_node.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- src/transaction_manager/transaction_manager.cpp
- src/transaction_manager/transaction_manager.hpp
Any time transaction status is updated based on the current transaction status, get and update operation are now protected with a mutex inside of transaction manager to prevent a race condition where transactions status ends up in an incorrect state:
Example:
At the same time transaction arrives with gossip and with syncing in executed block:
1. Syncing thread asks for a transaction status and gets unknown
2. Gossip handling thread asks for a transaction status and gets unknown
3. Syncing thread updates the status to finalized
4. Gossip thread updates the status to in_queue
With the added mutex this scenario is not possible
> fix: update transaction status correctly

- src/consensus/pbft_manager.cpp
when proposing a new pbft block sync block should only contain non-finalized transactions and use those to correctly calculate order hash
> fix: calculating trx order

- src/consensus/pbft_manager.cpp
- src/storage/db_storage.cpp
Getting a transaction had a race condition that if asking first in non-finalized transactions and after in finalized at the exact time when a transaction is finalized it could lead to a missing transaction assert. Reverting the order fixes the issue.
Additional logging added for the order hash issue
> fix: get transaction race condition

- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/consensus/sync_block.cpp
- src/consensus/sync_block.hpp
- src/consensus/vote.cpp
- src/consensus/vote.hpp
- src/network/network.cpp
- src/network/network.hpp
- src/network/rpc/Test.cpp
- src/network/tarcap/packets_handlers/vote_packets_handler.cpp
- src/network/tarcap/packets_handlers/vote_packets_handler.hpp
- src/network/tarcap/taraxa_capability.cpp
- src/network/tarcap/taraxa_capability.hpp
- src/node/full_node.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- tests/final_chain_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
- tests/pbft_manager_test.cpp
- tests/vote_test.cpp
Fix verified votes consume lots of memory issue when PBFT cannot make consensus on voting
1. Only save verified votes hash in verified table
2. PBFT manager will not get all verified votes for current round, only get number of votes 
> perf(votes): rewrite verified votes table

- src/consensus/pbft_manager.cpp
Enables asynchronous blocks execution when syncing. The functionality was already implemented but it was not used when syncing.
> chore:enable asynchronous execution

- src/final_chain/final_chain.cpp
- src/util/thread_pool.cpp
What was happening is that, FinalChainImpl has TP with just one thread and it also sends sheard_ptr of itself to TP. In some cases while running tests exception happened, because  FinalChainImpl destructor tied to destroy TP while it was inside, so it was basically calling join on itself
this resolves https://github.com/Taraxa-project/taraxa-node/issues/1152
> fix(thread_pool): fix crash when trying to join ourselfs

- src/cli/testnet_config.hpp
- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/dag/dag_block_manager.cpp
- src/network/sync_block.hpp
When a pbft block with incorrect order hash was pushed into a chain the push would fail but at the same time dag blocks within the pbft block were removed from the non-finalized set with method setDagBlockOrder, breaking the DAG and network got stuck. The check for incorrect order hash is now moved before calling setDagBlockOrder
> fix: dag order

- src/consensus/pbft_manager.cpp
- src/final_chain/final_chain.cpp
- src/final_chain/final_chain.hpp
- tests/full_node_test.cpp
- tests/network_test.cpp
Check that final chain thread is stopped before destroying objects
> fix: finalchain destructions

- src/config/config.cpp
- src/config/config.hpp
- src/network/tarcap/packet_types.hpp
- src/network/tarcap/packets_handlers/dag_packets_handler.cpp
- src/network/tarcap/packets_handlers/dag_packets_handler.hpp
- src/network/tarcap/taraxa_capability.cpp
- src/network/tarcap/threadpool/priority_queue.cpp
Removing functionality of sending only dag block hashes as part of gossiping as it makes it very difficult to synchronize dag blocks order. This functionality does not make sense in an environment where a lot of dag blocks are proposed in parallel in short amount of time.
> chore: remove dag block hash packets

- src/consensus/pbft_chain.cpp
- src/consensus/pbft_manager.cpp
- src/consensus/pbft_manager.hpp
- src/consensus/sync_block.cpp
- src/consensus/sync_block.hpp
- src/final_chain/final_chain.cpp
- src/network/rpc/Taraxa.cpp
- src/network/rpc/eth/Eth.cpp
- src/network/tarcap/packets_handlers/pbft_blocks_sync_packet_handler.cpp
- src/node/full_node.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- src/transaction_manager/transaction.cpp
- src/transaction_manager/transaction.hpp
- tests/final_chain_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
- tests/util_test/util.hpp
This PR enabled RLP cache for transactions. Transaction RLP serialization during syncing accounted for 28% of cpu usage and after this change just to 16%.
Before:
After:
> Trx rlp cache

- src/consensus/block_proposer.cpp
- src/consensus/block_proposer.hpp
- src/consensus/pbft_manager.cpp
- src/dag/dag.cpp
- src/dag/dag.hpp
- src/dag/dag_block_manager.cpp
- src/dag/dag_block_manager.hpp
- src/network/rpc/Taraxa.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
- tests/dag_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_manager_test.cpp
- tests/util_test/util.hpp
This PR improves DAG block status handling and completely removes redundant DB data. It is based on this PR https://github.com/Taraxa-project/taraxa-node/pull/1118 this should be merged before!!!
"dag_block_period": 38520098,
"dag_blocks": 2880577,
"dag_blocks_index": 31480472,
REMOVED  ----> "dag_blocks_state": 2028541,   <---- REMOVED
REMOVED  ----> "dag_finalized_blocks": 27889837,   <---- REMOVED
"default": 0,
"dpos_proposal_period_levels_status": 3301,
"final_chain_blk_by_number": 7247123,
"final_chain_blk_hash_by_number": 745559,
"final_chain_blk_number_by_hash": 744199,
"final_chain_log_blooms_index": 4164726,
"final_chain_meta": 3253,
"final_chain_receipt_by_trx_hash": 229678726,
"final_chain_replay_protection": 0,
"final_chain_transaction_count_by_blk_number": 391413, …
> Improve dag status

- src/cli/testnet_config.hpp
- src/dag/dag.cpp
- src/storage/db_storage.cpp
- src/storage/db_storage.hpp
In recoverDag method dag blocks need to be added to memory DAG in correct order. Pivot and tips need to be added before the block it self. This is done by adding non finalized blocks sorted by level.
> fix: recover dag order

- src/consensus/pbft_manager.cpp
- src/dag/dag_block_manager.cpp
- src/network/tarcap/taraxa_capability.cpp
Fix for incorrectly marking node malicious
Temporary disabling marking dag blocks as invalid to investigate issues with it
Temporary disabling marking nodes malicious to investigate issues with it
> fix: sync block validation and malicious issues

- Dockerfile
Builds started to fail due to expired SSL certificate on conancenter this disables ssl verification.
The final fix was to add ca-certificates package to the apt install step in docker file.
> chore(conan): Fix issue with expired certificate on conan center

- libraries/core_libs/consensus/include/dag/dag.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- tests/dag_test.cpp
- tests/full_node_test.cpp
getDagBlockOrder only works correctly if it is called for the current period. New parameter was added to specify for which pbft period we request the order. If the period is not the expected one, error is logged and empty response is returned.
In general we should not be calling getDagBlockOrder with incorrect period. Additional changes in pbft_manager should be done to ensure this
> fix: get dag order with correct period

- libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
If block is missing a tip or pivot the transactions included in the block are now saved and not dropped
> fix: missing transaction

- libraries/storage/include/storage/storage.hpp
- libraries/storage/src/storage.cpp
- libraries/types/pbft_block/src/sync_block.cpp
Since node only save 2t+1 cert votes for each finalized PBFT block. When node receive a synced PBFT block from peers, if the number of cert votes are not 2t+1, or any cert votes failed checking conditions, the whole cert votes bundle should be invalid and failed immediately.
> Check Synced Cert Votes

- .circleci/config.yml
- Dockerfile
Dependencies from the conan was rebuilt on every build because of different build type detection by conan-cmake. Fixed by setting build type to the conan profile
> build(conan): fix conan cache invalidation caused by different build type detection

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Fix for any PBFT proposal blocks, only use weighted index 0 for VRF sortition. Since vote will only use weighted index 0 for VRF sortition in PBFT proposal state. Before the fix node will propose PBFT blocks without votes related to
> PBFT proposal state only use weighted index 0 for VRF sortition

- .circleci/config.yml
- Dockerfile
- libraries/cli/include/cli/config.hpp
- libraries/cli/src/config.cpp
- libraries/config/include/config/config.hpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
Added new options `--rebuild-db-columns`, that will remove old columns from DB and node can continue working even if DB scheme changes.
IMPORTANT:  `COLUMN(default_column);` is introduced again (it was removed, maybe even by me) but it needs to be there. This is default column for rocks DB, that can not be change. Right now we have there all period data and that's not good. So this is probably BREAKING CHANGE
> chore(db): new option to remove old columns from DB

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/full_node_test.cpp
- tests/vote_test.cpp
This PR should optimize what votes are we saving to DB, so now on it is only our votes and the rest we will receive after the node restarts
> chore(vote_mngr): do not save all votes to DB

- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
This new setting should limit rocksDB memory usage, I think it is caused by `ulimit -n` that is set on our nodes to extreme number `1048576`. With this setting we can limit number of open files ~= RAM consumption. I am not 100% sure, but I would like to deploy it to our testnet and let's see if this can help
> chore(db): max_open_files setting for DB, to limit memory usage

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Fix for incorrect vote type used in the shouldSpeak check
> fix: should speak vote

- programs/taraxa-bootnode/README.md
- programs/taraxa-bootnode/main.cpp
Add option --wallet for bootnodes, so we can specify their private keys
> Add wallet option for bootnode

- libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
As marking votes as know for peers is not sufficient (cache sizes 100k) and checking in verified/unverified queues also (invalid votes is not in either of them). I have introduced additional cache that show performance improvements. 
Checking in verified/unverified queues seems to be also quite slow.
TLDR: 
- processing function speed up 973 [us] -> 500 [us] = 48% !!!!
- amplifying level of IN:OUT packets 4.29 -> 1.45 = 66% !!!!
BEFORE: 
IN: 
```
[VotePacket -> total_count: 27371, total_size: 6351761 [B], avg_size: 232 [B], processing_duration: 26654686 [us], avg processing_duration: 973 [us], tp_wait_duration: 2537067446395 [us], avg tp_wait_duration: 92691806 [us]]
```
OUT
```
[VotePacket -> total_count: 117504, total_size: 27265706 [B], avg_size: 232 [B], processing_duration: 0 [us], …
```
> chore(vote): add know votes to vote packet handler

- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
Filtering sync irrelevant packets was not working correctly
> fix: filter sync irrelevant packets

- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
Mark blocks which fail vdf and dpos verification as invalid. Block that have missing transactions could be valid so just clear them from seen blocks.
> fix: mark invalid block

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/network.hpp
- libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
Deep sync state will be true until we are completely synced. With this change, the deep sync state will be set to false as soon as syncing gets close to being synced.
> Deep sync improvement

- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
Keep old VrfParamsChanges to validate old dag block correctly
> fix: not remove old VrfParamsChanges to validate old dag block correctly

- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
This issue is already fixed on develop with a deep syncing feature. This is only a hotfix for the testnet for votes memory leaks.
> fix: votes memory leak on syncing

- libraries/cli/include/cli/testnet_config.hpp
Adds all initial Taraxa nodes to genesis block. Will use this info in other apps like the delegation worker in order to spread out the number of votes to all nodes
> chore(config): delegate to six Taraxa nodes in genesis block

- libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
- libraries/core_libs/storage/src/storage.cpp
- tests/transaction_test.cpp
Transactions that were already finalized in a pbft block were incorrectly included in the nonfinalized_transactions_in_dag_ structure and in db when transactions were included in another dag block creating a memory leak. Fix is checking if the transactions is already in the db before saving it.
The fix includes removing all incorrectly saved transactions in recoverNonfinalizedTransactions from DB on restart so that existing node data is properly processed on startup. This part can later be removed
> Nonfinalized trx fix

- libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_syncing_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
Race condition flow:
1. we choose a peer https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp#L36
2. peer is disconnected https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/core_libs/network/src/tarcap/taraxa_capability.cpp#L273
3. we send a request (witch fails) https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp#L59
4. We never restart as pbft_sync is always true https://github.com/Taraxa-project/taraxa-node/blob/develop/libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp#L27
> chore(syncing): race condtion in syncing

- libraries/core_libs/consensus/include/dag/sortition_params_manager.hpp
- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- libraries/vdf/include/vdf/config.hpp
- libraries/vdf/src/config.cpp
- tests/sortition_test.cpp
This PR is made only for the testnet to enable difficulty adjustment changes in a hard fork without changing the db format. A different change is needed for develop branch.
k_threshold_testnet_hard_fork_period defines the period on which the vrf upper bound will be reduced even though lower bound reached 0. To implement this without modifying the current testnet db format, there is a range constant k_threshold_range which defines a constant difference between lover and upper bound to be able to recover once the lower bound reaches 0 and upper bound is reduced below this range.
Upper bound can now be reduced up to k_threshold_upper_min_value = 0x50
> chore: difficulty adjustment testnet fork

- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/config/src/chain_config.cpp
- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- libraries/vdf/include/vdf/config.hpp
- libraries/vdf/src/config.cpp
- libraries/vdf/src/sortition.cpp
- tests/crypto_test.cpp
- tests/full_node_test.cpp
- tests/sortition_test.cpp
- tests/util_test/util.hpp
Improvement to enable vrf upper range to be lowered up to a minimum level even if lower bound is at zero
> chore: vrf range improvement

- Dockerfile
adds taraxa-bootnode binary to final image
> chore(docker): adds taraxa-bootnode binary to final image

- libraries/core_libs/network/include/network/tarcap/packets_handlers/dag_block_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
When we received dag block with missing something from node A, we request missing blocks, but when meanwhile we receive same block from node B,C ... we to the same thing. So, we basically DDoS ourselfs. I have create small cache that should solve this behaviour
> chore(dag): create seen cache to not request same block multiple times

- libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
I do know how is this happening, but we somehow end up without any syncing repose from peer (maybe this TP is overloaded?), because we still received other packets from that peer. 
This should fix it.
> chore(syncing): hotfix for syncing without response

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Test reboot consensus nodes several times, that works well.
When nodes get partition and cannot make consensus, the exponential backoff could extend voting speed. After exceed maximum steps(current set as 13) the extend sleep time will get bigger. 
Testing logs:
0x00007faebcff9700 PBFT_MGR [2021-11-15 19:36:56.724661] INFO: Proposing 1 values of NULL_BLOCK_HASH #00000000… for round 1 by protocol
0x00007faebcff9700 PBFT_MGR [2021-11-15 19:36:58.057461] INFO: Soft votes 1 voting block #00000000… at round 1
0x00007faebcff9700 PBFT_MGR [2021-11-15 19:36:59.388582] INFO: Next votes 1 voting nodes own starting value #00000000… for round 1, at step 4
0x00007faebcff9700 PBFT_MGR [2021-11-15 19:37:00.720619] INFO: Next votes 1 voting nodes own starting value #00000000… for round 1, at step 6 …
> chore(pbft): uncomment code enable exponential backoff for advanced steps in PBFT

- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
This condition happens often if one block behind and at the same time a pbft block is pushed by pbft consensus and syncing at the same time. Unless restartSyincingPbft is called, node gets stuck in syncing state.
> fix: syncing stall

- libraries/core_libs/consensus/include/pbft/block_proposer.hpp
- libraries/core_libs/consensus/src/pbft/block_proposer.cpp
- libraries/types/dag_block/include/dag/dag_block.hpp
Use frontier(pivot and tips) for stale block selection. Using proposal period as before, stale block would be computed even if new blocks appear on the network.
> chore: check stale block proposal by frontier

- libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_syncing_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
requestPendingDagBlocks was not getting the correct node id to send the request for dag blocks because of a race condition in setting the syncing peer
> fix: dag sync

- CMakeLists.txt
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
On dag sync requests, eliminate sending duplicate transactions and transactions that are already finalized. Get transactions from db in a batch query only from column containing non-finalized transactions.
> chore: optimize dag sync

- libraries/core_libs/consensus/include/dag/sortition_params_manager.hpp
- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
Previous fix did not include case when we are syncing. The difficulty correction is now done on restart and when we reach block 155600
> chore: difficulty fix

- libraries/core_libs/consensus/include/dag/dag.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
On devnet one of the nodes experienced a deadlock which blocked some of the threads and the process ran out of memory.
This was caused by DagManager::mutex_ and TaraxaPeer::mutex_for_sending_dag_blocks_ mutexes which were invoked in reverse order on gossiping the blocks compared to syncing dag blocks.
I have excluded gossiping from the DagManager::mutex_ but in order to do that and preserve the order of the dag blocks being gossiped another mutex is used in addDagBlock which prevents proposed block to be gossiped at the same time as blocks we get from the queue.
> Dag sync deadlocalk fix v2

- libraries/cli/include/cli/default_config.hpp
- libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
- libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
I have refactored logging for the following log channels:
DAG_BLOCK_PH
DAG_SYNC_PH
GET_DAG_SYNC_PH
GET_PBFT_SYNC_PH
PBFT_BLOCK_PH
PBFT_SYNC_PH
TRANSACTION_PH
DAGBLKMGR
DAGMGR
Main focus is on logging on INFO level and any level above(WARN, ERROR)
These channels will now on INFO level provide all the data needed to track gossip and syncing for transactions, dag blocks and pbft blocks. INFO level logs are made to be as minimal as possible with no repetitions. Only new transactions and blocks are logged, any packets containing data that is already known are not logged on INFO level.
> chore: improve logging

- .circleci/config.yml
- libraries/aleth/libp2p/NodeTable.cpp
- libraries/aleth/libp2p/NodeTable.h
- libraries/cli/include/cli/config.hpp
- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/cli/src/config.cpp
- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/network/src/network.cpp
- tests/util_test/conf/conf_taraxa1.json
- tests/util_test/conf/conf_taraxa2.json
- tests/util_test/conf/conf_taraxa3.json
- tests/util_test/conf/conf_taraxa4.json
- tests/util_test/conf/conf_taraxa5.json
So idea is that node can report different IP (external IP), that should be use for discovery. I implemented basic mappings that will keep track of node ID and it's real ip (this could change) and real IP with external IP, so we know what should we report to the rest of the network
> Improved discovery

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
PBFT blocks proposal rate change to depends on number of stakes, not every delegation node has the same proposal rate anymore
> PBFT blocks proposal rate for develop branch

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Hi @justinsnapp, as your request, I cherry pick the PBFT exponential backoff and generate PR for Testnet branch.
In our case, for example like one node CN4 down many hours and cause PBFT stalled. Then restart CN4 and want to catch up with others nodes steps. This cannot help, and may need take longer time.
The benefits: could save space for many votes when PBFT stalled
The disadvantage: when more than 1/3 weighted nodes down, and restart nodes want to catch up. That may take longer time because votes not send often as before (in old approach, send out 2 votes every 2 seconds for each node)
> Exponential backoff testnet

- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/network/include/network/tarcap/shared_states/peers_state.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/peers_state.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
There is race condition between getting peer and getting pending peer as it can change those states between those 2 calls
> chore(peer): fix race condition in pending peers

- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
When processing a gossiped dag block for which we do not have a proposal period yet, it is safe to assume that we are not pbft synced in which case there is no need to keep this block in the queue which creates a loop that creates a lot of unneeded logs as well as it eats up CPU. Drop this block and expect to receive it again when fully pbft synced.
> chore: remove ahead block from queue

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
Verified votes retrieved from db on startup were broadcasted with net->onNewPbftVotes but on startup no peer is actually connected yet. As a temporary fix I delay the broadcast for 2 minutes when it is expected that there will be peers connected. A better fix is needed on develop.
> fix: initial vote sync

- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
When dag block fails validation it should always be dropped. There were some conditions when such a block was processed which was incorrect.
> chore: do not process dag block with missing tip/pivot

- libraries/core_libs/consensus/include/dag/dag.hpp
- libraries/core_libs/consensus/include/transaction_manager/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
- libraries/core_libs/network/include/network/network.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/get_dag_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- tests/network_test.cpp
- tests/util_test/util.hpp
When processing a getDagSyncPacket non finalized blocks are sent only with unique set of transactions that are not finalized or included in a previous DAG block. Other transactions should already be present on the peer requesting it.
There was a race condition where it was possible that between requesting dag blocks with getNonFinalizedBlocks and transactions with db_->getNonfinalizedTransactions(trx_to_query), some blocks were actually finalized which would lead to sending some missing transactions in the packet. This has been fixed that now blocks and transactions are retrieved with a new method DagManager::getNonFinalizedBlocksWithTransactions which ensures that blocks are retrieved under the DagManager mutex which ensures that blocks cannot be finalized while retrieving this data.
At …
> fix: race condition in retrieving blocks with transactions

- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
- libraries/core_libs/consensus/src/transaction_manager/transaction_manager.cpp
Any dag block that was saved in the db on syncing will not be in the seen_blocks cache. Checking db for valid tips/pivot is needed. This should not hurt performance since pivotAndTipsValid is called very rarely on a race condition in verifying both a block and it's tip/pivot at the same time. This only happens on the initial dag sync.
> chore: dag block validation

- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/common/include/common/util.hpp
- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/get_dag_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/transaction_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/shared_states/peers_state.hpp
- libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/peers_state.cpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/tarcap_threadpool_test.cpp
Malicious nodes are now marked as malicious for a specific amount of time defined in network_peer_blacklist_timeout. The default is 600 seconds(10 minutes). It is also possible to disable blacklisting with disable_peer_blacklist flag. Main reason for this is that we had cases that nodes were acting malicious because of a bug or an old version. It could be even because of the config file misconfigured. Any such node could in time be corrected and it should not be blacklisted forever.
All of the blacklisting is memory bases so any node restart will clear it as well.
PR handles most of the cases where invalid data is sent, like invalid blocks, transactions with incorrect difficulty and similar. Node sending blocks with missing transactions. The PR does not handle DDOS attacks where valid …
> chore: malicious nodes handling

- conanfile.py
this change in https://github.com/conan-io/conan-center-index/pull/9135 mpir package broke our building as it gmp is now provided by 2 packages
> chore(conan): fix latest change in conan recipes

- libraries/core_libs/network/include/network/tarcap/shared_states/syncing_state.hpp
- libraries/core_libs/network/src/tarcap/shared_states/syncing_state.cpp
Based on core dump from issue, it is obvious that it crashed inside atomic that was accessed from line:
`deep_pbft_syncing_ = (peer_->pbft_chain_size_ - current_period >= kDeepSyncingThreshold);`
that means it can be only `peer_->pbft_chain_size_`, but gdb printed valid value for this variable. In the next frame it has weird address though and then we found out that `peer_` could have been overridden in the meantime and thats how we found out the race condition for peer_ variable...
> fix(syncing_state): fixed race condition inside set_pbft_syncing

- libraries/cli/include/cli/config.hpp
- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/cli/include/cli/tools.hpp
- libraries/cli/src/config.cpp
- libraries/cli/src/tools.cpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
Moving gossip/syncing logs from INFO to DEBUG and DEBUG to TRACE to avoid extensive logging on INFO level.
Added additional configuration that is off by default where these networking debug logs can easily be turned on.
> chore: move extensive network logs from info to debug level

- libraries/core_libs/storage/src/storage.cpp
Delete range in cleanupDagEfficiencies had an incorrect parameter of 0 instead of Slice object pointing to uin64_t 0, this could have caused undefined behaviour on what is actually deleted.
> fix: cleanup efficiency

- libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_manager_test.cpp
- tests/util_test/samples.hpp
- tests/util_test/util.hpp
Fixes: #1588
Fixes: #1568
- sync_five_nodes -> now we are waiting until initial transaction are executed before we continue with the test
- DISABLED_transfer_lot_of_blocks -> @mfrankovi PR should fix that
- node_full_sync -> now not checking for syncing due to empty PBFT blocks but checking non empty blocks
- pbft_manager_run_multi_nodes -> checking for non-empty blocks and increase timeouts because of execution can takes more time
>  stabilize  tests

- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/mainnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/consensus/include/dag/dag.hpp
- libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
- libraries/core_libs/consensus/include/pbft/pbft_chain.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/get_pbft_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/status_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/rpc/Test.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_syncing_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/dag_test.cpp
- tests/full_node_test.cpp
Implements light node functionality by deleting old data from period_data column which takes most of the disk space in the database.
light-node-history parameter in the config file defines how much period_data history is kept in the database. The rest is deleted.
As part of this a new feature of limiting inclusion of old/expired dag blocks into pbft is implemented.
> feat: light node

- libraries/core_libs/consensus/include/dag/sortition_params_manager.hpp
- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- tests/sortition_test.cpp
Efficiency was not correctly populated because ignored_efficiency_counter_ was not getting reset after each changing_interval. This made the calculation be based on full changing_interval and not just computation_interval. On restart it was reset which made nodes that restarted have different efficiency data which corrupted difficulty calculation.
The fix is only reseting the ignored_efficiency_counter_ to 0 but it also contains added tests to make sure that both efficiencies and params_changes_ that are kept in memory have same values before and after the restart.
> fix: efficiency cache

- libraries/core_libs/consensus/src/pbft/block_proposer.cpp
- libraries/vdf/include/vdf/sortition.hpp
- libraries/vdf/src/sortition.cpp
- tests/crypto_test.cpp
- tests/dag_block_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
Fixes: #1659 
Please check also https://github.com/Taraxa-project/taraxa-vdf/pull/9
I can not say for sure if this was the case, but I know exact spot. So I think flow was like this:
1. We execute std::sync
2. async is still not executed ...
3. some of the condition applied
4. we want to cancel execution but pointer is empty
5. Segfault
> fix: improve async cancellation

- libraries/cli/include/cli/default_config.hpp
- libraries/cli/include/cli/devnet_config.hpp
- libraries/cli/include/cli/mainnet_config.hpp
- libraries/cli/include/cli/testnet_config.hpp
- libraries/config/src/chain_config.cpp
- tests/full_node_test.cpp
Change threshold range from 50% to 80% which reduces the chance for omit vdf block from 50% to 20%. This should make the dag block production more smooth
Update testnet config timestamp
> chore: omit vdf config change and testnet timestamp change

- libraries/core_libs/network/rpc/eth/Eth.h
- tests/network_test.cpp
after recent clang tidy clean-up I have and issue to build latest develop
```
/home/matus/dev/taraxa-node/libraries/core_libs/network/rpc/eth/Eth.h:21:8: error: defaulted move assignment for ‘taraxa::net::rpc::eth::Eth’ calls a non-trivial move assignment operator for virtual base ‘taraxa::net::EthFace’ [-Werror=virtual-move-assign]
21 | struct Eth : virtual ::taraxa::net::EthFace {
```
second change should improve test
> chore: small updates after clang-tidy

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- tests/network_test.cpp
- Improved execution of one problematic network_test
- fix condition for nonce checking, after lot of debugging I found out that EVM does not return nonce, but number of transactions execute so basically lastNonce - 1
> Improve tests

- libraries/common/include/common/constants.hpp
- libraries/config/include/config/config.hpp
- libraries/core_libs/consensus/include/dag/dag.hpp
- libraries/core_libs/consensus/include/dag/dag_block_manager.hpp
- libraries/core_libs/consensus/include/pbft/pbft_chain.hpp
- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/dag/dag_block_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/dag_test.cpp
- tests/full_node_test.cpp
There were several issues related to using period limit for dag blocks expiry. New approach is using a dag block level limit which is much cleaner and easier to check without a need to pull proposal period from the database for each dag block. Level limit is based on the level of the last anchor from the last pbft block in the chain.
Dag expiry limit and max dag levels per period can now be configured to be able to test them without a need to have a large dag and large pbft chain.  This allowed for simpler light node tests and creation of additional test in dag_test which tests dag expiry.
> chore: dag expiry and light node tests improvements

- libraries/common/include/common/constants.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/common/packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/pbft_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/transaction_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/rpc/Taraxa.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
Limit number of votes in a single packet and throttle votes packets not to send too many votes at once. The same is already done for transactions.
> chore: limit number of votes in packet

- libraries/core_libs/consensus/src/dag/dag.cpp
In test pbft_next_votes_sync_in_behind_round there was a segfault caused by DagManager calling trx_mgr after it was set to nullptr. Fix is not to set trx_mgr to nullptr. I am not sure what was the reason this was ever set to nullptr. It was actually done by a commit by me 2 years ago when the code base was different.
> fix: pbft_next_votes_sync_in_behind_round seg fault

- libraries/cli/include/cli/devnet_config.hpp
Increase number of slots on devnet as nodes failed to connect to each because of this `Disconnect (reason: Peer had too many connections.)`
> chore: increase number of peer slots on devnet machines

- libraries/aleth/libp2p/NodeTable.h
Lot of our request times out on devnet after recent location changes. Let's try this and if this does not help I need to look why discovery does not work (where are 300ms wasted)
> chore: increase timeout for discov protocol

- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- libraries/core_libs/network/include/network/network.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/transaction_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/node/src/node.cpp
- tests/network_test.cpp
- tests/p2p_test.cpp
- tests/transaction_test.cpp
Transactions with low nonce and insufficient balance should not be placed into transactions pool to propose dag blocks from but at the same time there are scenarios when such transactions might be needed by incoming dag blocks.
My proposed solution is keeping these transactions in a separate memory map. Once a dag block arrives if it is missing a transaction it will check in these low nonce and insufficient balance transactions as well.
These transactions will expire if no dag blocks arrive after a certain number of periods are executed.
Insufficient balance transactions have different handling than low nonce because there is a chance that such transactions will have sufficient balance after a new block is executed so on block execution they might be moved to regular transactions pool if …
> chore: low nonce and insufficient balance transactions handling

- .github/workflows/docs.yaml
Make doxygen docs available on gh-pages
We still need to enable github pages in settings.
created a github action
> docs: Add gh-actions to build and publish docs on gh-pages

- libraries/core_libs/consensus/src/dag/dag.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/include/network/network.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/pbft_block_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/p2p_test.cpp
- tests/pbft_chain_test.cpp
- tests/util_test/util.hpp
- tests/vote_test.cpp
Use templated getSpecificHandler method to get rid of those pointer casts in network and tarcap classes
Fixed https://github.com/Taraxa-project/taraxa-node/issues/1722
> Cleanup pointer casts in network and tarcap classes

- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- tests/full_node_test.cpp
This test was intermittently failing because of very small values of max_levels_per_period and light_node_history which were set to these low levels so that the test can be performed quickly but it could cause one of these issues:
1. One node would get ahead the second one with dag blocks and would send ahead/future block which would cause the disconnect
2. One node would get ahead the second one with pbft chain and light node would delete old blocks so the other nodes could not sync from the light node
Fix is only sending a new transaction to a node if both nodes have same pbft chain size. Setting as light node, node that is not eligible to propose dag blocks not to allow the proposer to create dag blocks faster than other blocks process them.
Besides the test fix, I have also changed …
> clear_period_data test fix

- libraries/core_libs/consensus/src/dag/block_proposer.cpp
If a block was successfully proposed there should not be any delay in proposing next block. The comment was not matching the code.
> chore: proposal delay adjust

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/pbft/period_data_queue.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/period_data_queue.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/pbft_sync_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
Currently we have a bug and for the first synced PBFT block we do not validate rewards votes. This PR should handle this case
> chore: fix handling of rewards votes for in special edge case

- libraries/cli/include/cli/config_jsons/default.json
- libraries/cli/include/cli/config_jsons/devnet.json
- libraries/cli/include/cli/config_jsons/mainnet.json
- libraries/cli/include/cli/config_jsons/testnet.json
- libraries/config/include/config/dag_config.hpp
- libraries/config/src/dag_config.cpp
- libraries/core_libs/consensus/include/dag/block_proposer.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/dag/block_proposer.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- tests/full_node_test.cpp
- tests/pbft_manager_test.cpp
- tests/transaction_test.cpp
Hard transaction limit of 250 transactions in a DAG block is removed since dag gas limit is the mechanism used to limit DAG blocks size
Gas limit for dag block was refactored to fix an existing bug and make it more efficienct
> chore: remove dag transaction limit and refactor dag block gas limit

- libraries/config/include/config/state_api_config.hpp
#1836 
This is happening because unordered_map doesn't guarantee elements order. So sometimes it is different
> fix: change of genesis hash because of unordered_map reordering

- libraries/common/include/common/constants.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
Anything running under transaction_mutex in transaction_manager can be a major bottleneck for high TPS load.
transaction_accepted_.emit is moved out mutex since there was no need to run it under mutex.
Estimating transaction gas done under transaction mutex was a major bottleneck for transactions processing since estimation takes time. To avoid that batch of transactions from memory pool is retrieved and estimation is now done outside of mutex. I made an assumption that dag block gas limit divided by 21000 is max number of transaction we can fit under a single DAG block. I am not sure if this is a valid assumption. Is it possible to have transaction that does not take at least 21000 gas?
With these changes I am able to get  over 20k TPS processed in a single node
> chore: optimize transactions processing

- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_block_packet_handler.cpp
Sending reward votes was under a loop for no reason which created two issues:
1. Calling it unnecessary multiple times
2. Not sending votes at all if pbft block is known to other connected nodes
> chore: reward votes gossip improvement

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
We have a special case, when reward votes in `period_data` not verified.
Scenario:
1. Node was out of sync 2 block (blocks N and N+1)
2. node receive 2 sync blocks (blocks N and N+1)
3. meanwhile it also receive pbft block  N "normal" way not via syncing
4. then when it runs `processPeriodData` it will hit condition `pbft_chain_->findPbftBlockInChain(pbft_block_hash)` and that means that `cert_votes` structure (cert_votes for N == previous_block_cert_votes N+1) is not verified, so also not `previous_block_cert_votes` for block N+1
> bugfix: covering special case that happened on devnet

- for_devs/local-net
- libraries/common/include/common/types.hpp
- libraries/vdf/src/sortition.cpp
- tests/full_node_test.cpp
- tests/transaction_test.cpp
- tests/util_test/node_dag_creation_fixture.hpp
- tests/util_test/samples.hpp
During some tests I found a few issues:
1. In `local-net` script `address` and `vrf_key` was reordering sometimes and was leading to incorrect behaviour. For example if that was happening for 1 boot-node then it just can't finalize blocks because of not enought votes(incorrect address was specified in config). If few became incorrect then it wasn't starting because of `Validator already exist` error
2. Found that `str2bytes` was working incorrectly in my new test, so removed this and replaced it with `dev::fromHex` method that we already have. Did the same thing with `bytes2str` just because we already have `dev::toHex`
> Minor fixes

- tests/full_node_test.cpp
Light node test was sometimes failing. I have found and fixed two such issues and now it is passing 100/100 on my machine. I did not find anything wrong with the loght node implementation, only with the test itself.
Issues fixed:
1. Due to small light_node_history in test sometimes data would be deleted before it was synced to the other node. To prevent this transactions are now inserted into a non-light node and light node is the one that is syncing
2. There was a race condition between creating a new pbft block and deleting old blocks in a light node. Fix is simply allowing one extra pbft block to be present in a light node by increasing the limit that we verify in line 1609
> chore: light node test improvement

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Votes need to be verified for finalization but if the period is already pushed to pbft chain reward votes should not be added to vote manager because this corrupts the node since it adds reward votes for previous period while at the same time vote manager can already contain reward votes from current period which than incorrectly mixes votes from multiple periods.
> fix: corrupt reward votes

- libraries/core_libs/consensus/include/pbft/node_face.hpp
- libraries/core_libs/consensus/include/pbft/round.hpp
- libraries/core_libs/consensus/include/pbft/step/step.hpp
- libraries/core_libs/consensus/src/pbft/round.cpp
- libraries/core_libs/consensus/src/pbft/step/step.cpp
- libraries/logger/CMakeLists.txt
- libraries/logger/include/logger/logger.hpp
- libraries/logger/include/logger/shared_logger.hpp
Share same created logger objects between all steps and rounds to not create it every time
> feat: share same logger objects between steps and rounds

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
When verifying reward vote verify that this is a cert vote which has the same round as the round that previous pbft block pushed in the chain was cert voted on
> chore: verify reward votes round

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
if  anchor_hash was NULL_BLOCK_HASH, checkRewardVotes method was not used inside of PbftManager::compareBlocksAndRewardVotes_ so it was possible to push a block with reward votes missing
> fix: reward votes check

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
As noticed on devnet although this happens rarely it is possible that the same pbft block can be cert voted and pushed into chain on different nodes in different rounds. This means that it is possible that reward votes for next proposed pbft chain which are cert voted of the previous block can be in different rounds.
The changes in this PR allow us to save and gossip reward votes from different rounds as long as they point to the correct hash of the previous pbft block.
However on proposing a pbft block we only choose to include reward votes from the round that the proposer has cert voted previous block on. So reward votes included in pbft block will always have the same round.
> chore: allow rewards votes with different rounds

- libraries/core_libs/consensus/src/dag/dag_manager.cpp
This assert was incorrect. There is no valid reason why frontier_.pivot could not point to expired dag block and if this is the case it should be expired and removed. After validateBlockNotExpired is run, frontier value is always updated to a new proper value. So it should be safe to remove this assert.
> chore: remove incorrect assert in dag expiry

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
I have renamed reward_votes_pbft_block_round_ to last_pbft_block_cert_round_ because this variable actually keeps the round in which we cert voted last pbft block.
In VoteManager::addRewardVote we would save any reward vote to last cert vote table but only votes of the same round last block was cert voted on should be kept there since it is used to serve sync requests from other nodes.
> chore: cert vote choosing round

- libraries/core_libs/network/src/tarcap/stats/packets_stats.cpp
While looking into devnet I've noticed received == sent packet stats.
> chore: fix sent packet stats

- .gitignore
Add cache dir of ccls code indexer to .gitignore
> chore: add ccls cache dir to .gitignore

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- tests/vote_test.cpp
Always use chain_size + 1 as period in any next vote. Thanks to this we should be able to determine period in new round:
- if node sees 2t+1 next votes with period 10 in round 20, it moves to the round 21 with determined period 10. Node's pbft consensus is blocked until it's chain size is >= 9...
if half of the nodes pushed block into the chain in round 20 and other half did not, 50% of the next votes will have period N and other 50% N+1, which might cause the network to not advance into the next round until some of the 50% of nodes that did not push block sync up and create next vote with N+1 period so we will actually have 2t+1 next votes with some value...
> Fix different periods

- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/dag_block_test.cpp
- tests/transaction_test.cpp
When verifying received DAG block all transactions need to be retrieved from pool or database to be able to verify block weight. If there is a lot of transactions in the block that are already finalized these transactions are retrieved from the database from period data which is very slow. A block with 10000 transactions took almost 3 minutes to verify when transactions are pulled from period data.
Following optimizations are made:
Check both the pool and nonfinalized_transactions_in_dag_ where transactions are stored in memory before checking the db for finalized transactions.
Keep last finalized block transactions in memory since DAG block might often have transactions which have just been finalized
When actually retrieving transactions from database, group transactions per period so …
> chore: optimize dag verify

- libraries/types/transaction/src/transaction.cpp
On stress testing the devnet two nodes crashed with trace:
#8  0x00007f58a7476558 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f58a7dbd864 in taraxa::Transaction::getSender (this=<optimized out>) at /opt/taraxa/libraries/types/transaction/src/transaction.cpp:112
sender_initialized_ was set to true before we actually initialized sender causing getSender to fail and throw exception if there was another call to getSender between setting sender_initialized_  to true and actually saving the sender_ value.
> fix: transaction get sender

- libraries/core_libs/storage/src/storage.cpp
Huge RLP data was copied inside of loop. With the change transactions retrieval from period data is 20x faster
> chore: optimize trx retrieval

- libraries/cli/CMakeLists.txt
Before this change we was regenerating config strings only after manual calling of cmake command. That could be a problem in some situations during local tests, etc. 
So right now if json file was changed reconfiguration is triggered automatically
> fix: reconfigure project after change of JSON conffiguration files

- libraries/core_libs/network/include/network/tarcap/threadpool/packets_blocking_mask.hpp
- libraries/core_libs/network/src/tarcap/threadpool/packets_blocking_mask.cpp
- libraries/core_libs/network/src/tarcap/threadpool/priority_queue.cpp
- libraries/types/dag_block/include/dag/dag_block.hpp
- libraries/types/dag_block/src/dag_block.cpp
- tests/tarcap_threadpool_test.cpp
Block processing of same dag blocks concurrently.
For large dag blocks this was causing a major bottleneck with the same block being verified multiple times in parallel on multiple threads since all connected nodes might send it in short time frame.
> chore: optimize dag block processing

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
There was a race condition where if some thread called addRewardVote between calls to:
db_->addLastBlockCertVotesToBatch and vote_mgr_->replaceRewardVotes(std::move(cert_votes))
reward vote from the old period would get saved into Columns::last_block_cert_votes and it would never be deleted.
The fix is that replaceRewardVotes now replace the votes in memory before deleting them from the db. After this only new reward votes are accepted into VoteMgr and old votes are deleted from the db with the return value of replaceRewardVotes.
On node restart last_block_cert_votes vote are verified that they point to the last block in the chain before being stored in memory as reward votes
> fix: reward votes replace

- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
On high tps tests on devnet, there is still some slow processing when verifying dag blocks. This happens when verifying DAG blocks which include a lot of transactions that are already finalized.
last_finalized_block_transactions_ was cleared even for blocks that had no transactions or a small number of transactions so instead of keeping only last block transactions in memory we now keep up to 50k recently finalized transactions in memory before clearing it.
> chore: improve trx retrieval

- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- tests/full_node_test.cpp
Fix sporadic fails of `transaction_pool_overflow` test by increasing count of validators. Without this change all consensus is done by one node and other is permanently syncing from it. Because of this we could be in situation when nodes has different chain size and dag syncing isn't working because we are still in pbft syncing process
> fix: sporadic transaction_pool_overflow fails

- libraries/core_libs/consensus/include/pbft/period_data_queue.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/period_data_queue.cpp
Fix an issue where old block can get stuck in the sync queue and prevent syncing new blocks
> fix: sync queue with old block

- tests/full_node_test.cpp
Improve reliability of test.
Reduce the speed up of test from x10 to x5 to avoid two nodes being out of sync.
Increase the margin for checking blocks deleted since it can change slightly in time due to creation of new blocks.
> chore: light node test

- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
Remove getting finalized transactions from proposal since it is not needed.
Fill seen_blocks_ cache on startup so that getting dag blocks in pbft block proposal is served from cache and not db
Cache sender in transactions on startup since getSender is expensive to avoid doing it on proposing pbft blocks
> chore: optimize pbft block proposal

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
- tests/network_test.cpp
- tests/pbft_manager_test.cpp
Pbft block contains an order_hash which previously was created from order of dag blocks and order of transactions. This creates performance issues when pbft block has large number of transactions(100k transactions) at two points in consensus process:
1. On proposing pbft block large number of transactions needed to be retrieved and sorted to be able to generate the order_hash
2. On verifying proposed pbft blocks large number of transactions needed to be retrieved and sorted to be able to verify the order_hash
This change has removed transactions from the order_hash. Order hash now is only order of dag blocks. It is assumed that the order of dag blocks at same period will always have same set of unique non-finalized transactions.
By removing transactions from order hash these changes were …
> chore: optimize pbft propose and verify

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
1. In VotePacketHandler::process process next votes from previous round same as it is done in VotesSyncPacketHandler::process
2. In broadcastPreviousRoundNextVotesBundle rebroadcast all votes even though we think that other nodes know about it
3. broadcastPreviousRoundNextVotesBundle is called in secondFinish each 100 steps, changed it to 20 steps
In first and second finish we rebroadcast pbft block, reward votes and these next votes from previous round. And this is done each N steps, I am not sure if it makes sense to configure how often we do it or we just stick with hard coded values?
> chore: previous round next votes sync imrpovement

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/dag/block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/types/dag_block/include/dag/dag_block.hpp
- libraries/types/dag_block/src/dag_block.cpp
- tests/dag_block_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_manager_test.cpp
- tests/util_test/node_dag_creation_fixture.hpp
Pbft block proposal and verification is time sensitive for pbft steps.
Several recent changes were introduced to remove unneeded transactions processing in this process. To completely remove transactions processing from PbftManager::compareBlocksAndRewardVotes_ I have made changes in how we calculate gas limit for a pbft block. Previously gas limit was calculated for unique non-finalized transactions included in pbft block which required retrieving and processing these transactions for all transactions in pbft block. This is now changed and the gas limit check is done per weight of the dag block. This check is now no longer for unique transactions but for all transactions in dag block. I don't think we lose much with this change and we significantly improve the performance and we reduce …
> chore: optimize pbft block proposal and verification

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/common/ext_votes_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/get_votes_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/votes_sync_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_votes_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
This PR contains votes processing improvements (design adjustment) to prepare the code for merging propose vote packet with pbft block packet and. Based on these changes it is also very easy to fix period race condition for standard vs reward vote basically in few lines. This race condition was found by @mfrankovi and the proposed solution is in this PR https://github.com/Taraxa-project/taraxa-node/pull/2003
Thanks to the code adjustments in this PR, it was much easier and cleaner to fix this race condition.
Actual race condition fix commit:
https://github.com/Taraxa-project/taraxa-node/pull/2004/commits/cef1dc7b067b905aa3ceb08ff1388f1770fd82bf
> Votes processing improvement

- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
There is a possibility where synced block is already in chain that we are not actually synced. So this actually stops syncing. This can cause sync_five_nodes test to fail. Ensure that we are synced by calling restartSyncing for this case.
> chore: pbft syncing improvement

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
This change makes sure that a cert vote/reward vote being processed at the same time as period is advanced is not discarded.
> fix: reward votes race condition

- libraries/core_libs/consensus/include/pbft/pbft_chain.hpp
- libraries/core_libs/consensus/src/pbft/pbft_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
In PbftManager::proposePbftBlock_ loop to retrieve last anchor that is not null can take a long time if there is a long series of pbft blocks in the chain with null anchor. This can make pbft blocks be proposed too late and blocks may not be voted on.
The last non null anchor is now kept in pbft chain and can be quickly retrieved
> chore: optimize proposing pbft block

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
Checking reward votes in PbftSyncPacketHandler can sometimes fail if we are moving to the next period at the same time which should not be handled as malicious behaviors. If it does fail, a check is added if we actually moved to next period and in that case we restart syncing because it is very likely that we are already synced and restartSyncingPbft will verify this.
> chore: pbft sync while block cert voted

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/common/packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/status_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/vote_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/votes_sync_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
- tests/network_test.cpp
#1977 
After this change we are sending previous round next votes from `PbftManager` with regular votes packet. 
Node will accept `VotesSyncPacket` only from the nodes we requested
> feat: process VotesSyncPacket only from the nodes we requested

- libraries/core_libs/consensus/include/final_chain/final_chain.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
- tests/full_node_test.cpp
Have some fixes related to previously merged PRs:
1. Wait for `block - delegation_delay` in `waitForPeriodFinalization` to not slow down syncing
2. Check peer period in `broadcastPreviousRoundNextVotesBundle`
> fix: some issues related to previous PRs

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
// If node is not eligible to vote, always return true so pbft state machine never enters specific consensus steps
// (propose, soft-vote, cert-vote, next-vote). Nodes that have no delegation should just observe 2t+1 cert votes
// to move to the next period or 2t+1 next votes to move to the next round
> feat: do not enter consensus steps in case node is not eligible to vote

- libraries/core_libs/network/src/tarcap/packets_handlers/common/ext_votes_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/vote_packet_handler.cpp
I have noticed while doing stress tests some propose votes are not gossiped to all nodes. My suspicion is that in ExtVotesPacketHandler::onNewPbftVote we skip sending this vote because of the state of peer.second->pbft_chain_size_ and peer.second->pbft_round_ so I added additional logging there to confirm this.
I noticed in the logs on devnet that we were logging received same votes multiple times. I moved the check for duplicate votes before the logs and before deserialization of pbft block.
> chore: votes logging and minor optimization

- libraries/cli/include/cli/config_jsons/default.json
- libraries/cli/include/cli/config_jsons/devnet.json
- libraries/cli/include/cli/config_jsons/mainnet.json
- libraries/cli/include/cli/config_jsons/testnet.json
- libraries/config/include/config/config.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Original calculation for end_time_for_step was not good because LAMBDA_ms is not constant which could make several steps move very quickly and then some steps taking a very long time. 
New calculation only uses current LAMBDA to increase the time spent in the current step.
Reason for this:
loop_back_finish_state_ = elapsed_time_in_step > (int64_t)(2 * (LAMBDA_ms - POLLING_INTERVAL_ms));
being two times lambda is because this covers two steps since the delay is only added in second finish.
Besides this vote_accepting_steps is increased to 100 to prevent issues when nodes are down for a while and steps are not synchronized.
> chore: step end time

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Change to debug level since this is logged all the time on rpc nodes which have no voting weight. On develop this should be fixed once non-voting nodes will not go into the voting code.
> chore: change log level

- tests/full_node_test.cpp
- tests/util_test/samples.hpp
Bug in detect_overlap_transactions was serious because it actually corrupted the memory since we were writing outside of the range of nonces ovject since instead of being initialized with size nodes.size() and values 1, it was actually initialized with array with two values: nodes.size() and 1
Other changes are just ensuring nonce ordering in the tests
> fix: full node tests

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
It does not make sense to trigger pbft syncing from pbft after the latest changes. It was triggered when block validation failed during cert voting or pushing cert voted block but currently it is not possible that this fails due to missing previous pbft block as the current pbft period is determined based on chain_size + 1....
> chore: remove pbft syncing related code from pbft

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Transactions sort is supposed to happen before finalizing a block. This sort is expensive operation and it should only be done when finalizing the block not to slow down the consensus.
> fix: transaction sort

- doc/RPC.md
- libraries/core_libs/network/rpc/Test.cpp
- libraries/core_libs/network/rpc/Test.h
- libraries/core_libs/network/rpc/Test.jsonrpc.json
- libraries/core_libs/network/rpc/TestClient.h
- libraries/core_libs/network/rpc/TestFace.h
send_coin_transactions can create about 5000 transactions per second.
Transactions created will have most of the data the same other than:
nonce - specified nonce is increased for each transaction
receiver - is an array of receivers, if transaction count is greater than receiver, receivers are simply repeated
transaction_count - specifies number of transactions to create
> chore: rpc for creating large number of transactions

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- tests/full_node_test.cpp
- tests/transaction_test.cpp
Since sorting transactions for block proposal is an expensive operation, it is now only done when we propose a dag block and not on ever transaction insertion/removal. Algorithm for sorting is:
1. Order by gas price all the unique sender transactions with minimal nonce per account
2. Remove already ordered transactions from the set and move back to step 1 if there are still transactions remaining
On execution preserve the order of all the transactions that have correct nonce order. Any transactions with nonce order is reversed are moved to the back of the order and sorted by nonce.
> chore: implement nonce - gas price sorting

- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
When queue empty getOrderedTransactions would return an invalid transactions instead of 0 transactions. Fixed
> fix: ordered transaction get when queue empty

- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/pbft_sync_packet_handler.cpp
It is a valid possibility that block we receive in syncing could have already been pushed to the chain by consensus or by syncing that was interrupted so there is no need to restart syncing.
Calling restartSyncingPbft(true) unnecessarily restarts syncing and asks for the same data again. Since pbft sync packets come in series of ""network_sync_level_size": 25" same packets will be received multiple times which will lead to an infinite loop of calling restartSyncingPbft. This happened on devnet causing queue to be overfilled with these packets:
Low priority queue size: 137557
If synced block already in queue node now simply proceeds with syncing as if the block has been pushed to queue
> fix: pbft syncing

- libraries/core_libs/consensus/include/pbft/proposed_blocks.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/proposed_blocks.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/pbft_manager_test.cpp
Saving proposed blocks to db so that on restart all the proposed blocks from the last period/round can be reloaded.
I understand that there could be performance concerns about this change. I have added measuring pushing and erasing 100 blocks to db in the unit test. Results are:
Time to push 100 blocks: 927 microseconds
Time to erase 100 blocks: 132 microseconds
Rocksdb is very fast when dealing with columns that have small size by using its internal memory cache and delayed writes. So I do not believe speed should be an issue.
> chore: save proposed pbft blocks to db

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/pbft/proposed_blocks.hpp
- libraries/core_libs/consensus/include/pbft/soft_voted_block_data.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/proposed_blocks.cpp
- libraries/core_libs/consensus/src/pbft/soft_voted_block_data.cpp
- tests/full_node_test.cpp
- tests/pbft_manager_test.cpp
If (for any reason/bug) we lose block, there is an infinite loop in our pbft when:
1. nodes soft vote missing previous round next voted block
2. nodes next vote 2t+1 soft-voted block (from previous step)
3. in new round propose step is skipped as nodes are supposed to re-propose previous round next voted block but they cant as they dont have it
4. repeat the loop from step 1.
This is a state, from which we cant recover + we are saving proposed block in memory as well as db per period & round. So even if the block is actually saved on some node(e.g. period 1, round 2), we already moved forward multiple rounds so we are not able to get it due to that infinite loop I mentioned above - we might be trying to get some block hash for current period 1, round 10 but the block is saved for period …
> fix: do not soft vote missing block

- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
When transaction has the same nonce as a transaction in the transaction queue, it should either replace these transaction or be inserted into non_proposable_transactions_.
Since it was not included in non_proposable_transactions_ but it was incuded in known_txs_ even if it was received later again it was ignored.
It is always possible that a DAG block might come containing this transaction.
> fix: transaction with same nonce

- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
When dag blocks expires it was deleted from the db and the dag but it was not removed from seen_blocks_ cache.
DagManager::pivotAndTipsAvailable used seen_blocks_ cache to check for tips/pivot meaning it was possible to insert a dag block with expired pivot and tip and corrupt the DAG.
The fix contains a check in DagManager::recoverDag which should clean all invalid blocks from db on startup.
This fix also contains a minor fix where transaction was not removed from transaction cache in certain use case.
> fix: dag insertion

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
I had multiple errors during syncing:
```
0x00007f6698ff9640 942767c9… PBFT_MGR [2022-11-08 10:04:37.115966] ERROR: Unable to get CurrentDposTotalVotesCount for period: 42746. Period is too far ahead of actual finalized pbft chain size (42740). Err msg: Requested blk num:42741, last committed:42740
0x00007f6698ff9640 942767c9… PBFT_MGR [2022-11-08 10:04:37.116219] ERROR: Unable to get CurrentNodeVotesCount for period: 42746. Period is too far ahead of actual finalized pbft chain size (42740). Err msg: Requested blk num:42741, last committed:42740
0x00007f6698ff9640 942767c9… PBFT_MGR [2022-11-08 10:04:37.116346] ERROR: Unable to calculate 2t + 1 for period: 42746. Period is too far ahead of actual finalized pbft chain size (42740). Err msg: Requested blk num:42741, last committed:42740 …
```
> chore: change logs verbosity

- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_dag_sync_packet_handler.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
Once a peer has been dag synced, it should always send transactions and dag blocks in order so that dag block will never miss a transaction and dag block should never have a missing tip or pivot.
One exception to this rule is when transaction pool is full and node is forced to drop transactions. If transactions are dropped a DAG block might arrive with transactions missing. In this case there is a need to sync DAG again. At the same time allowing nodes to dag sync multiple times which is an expensive operations leaves us vulnerable to attacks. A limit is introduced that a peer can only ask for dag syncing once every kDagSyncingLimit(300) seconds.
Once transactions are dropped when transactions queue is full this is marked with transaction_overflow_time_ where node saves last time …
> chore: handle transactions queue overflow

- libraries/core_libs/consensus/include/dag/block_proposer.hpp
- libraries/core_libs/consensus/src/dag/block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
On block proposal only give up proposal if new dag block of same level was added to the DAG. Previous implementation would give up if an old DAG block was added to the DAG as well. This would unnecessary delay block proposal for both stale and non-stale blocks.
Pbft block leader selection now favors non-empty pbft blocks over empty ones.
> chore: optimize block proposal and pbft leader selection

- .circleci/config.yml
Use orb version for Circle Ci with latest fix for releasing prod charts.
> use fixed orb version for ci

- .circleci/config.yml
`build-docker-image` was triggered when using command for prnets:
- \deploy
- \cleanup
- \redeploy
Added conditions to job.
Added conditions to job.
> Fix: do not start build-docker-image when using prnet commands

- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/status_packet_handler.cpp
During monitoring I saw multiple times this error message:
`Light node is not able to serve our syncing request.` 
It also happened on brand new testnet, which was few hours old so this message should never be logged because minimu light node history is 7 days.
I added:
- additional info in log message to see some data
- changed the way we calculate min blocks count for min light node history
> chore: log additional info when disconnecting light node

- doc/RPC.md
- libraries/cli/include/cli/config_jsons/default.json
- libraries/cli/include/cli/config_jsons/devnet.json
- libraries/cli/include/cli/config_jsons/mainnet.json
- libraries/cli/include/cli/config_jsons/testnet.json
- libraries/config/src/chain_config.cpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/network/rpc/Test.cpp
- libraries/types/dag_block/src/dag_block.cpp
- libraries/vdf/include/vdf/config.hpp
- libraries/vdf/include/vdf/sortition.hpp
- libraries/vdf/src/config.cpp
- libraries/vdf/src/sortition.cpp
- tests/crypto_test.cpp
- tests/dag_block_test.cpp
- tests/full_node_test.cpp
- tests/hardfork_test.cpp
- tests/network_test.cpp
- tests/sortition_test.cpp
- tests/util_test/util.hpp
- Omit VDF removed
- Base for calculating VDF now includes the hashes of transactions in the dag block so it is only possible to use VDF in an unique block
> chore: vdf changes

- CMakeLists.txt
- CMakeModules/FindGMP.cmake
- CMakeModules/FindMPFR.cmake
- CMakeModules/ProjectLibFF.cmake
- CMakeModules/ProjectSecp256k1.cmake
- Dockerfile
- conanfile.py
- doc/building.md
- libraries/aleth/libdevcrypto/CMakeLists.txt
- libraries/types/vote/CMakeLists.txt
- libraries/vdf/CMakeLists.txt
- submodules/CMakeLists.txt
- tests/CMakeLists.txt
Replace conan built GMP and MPFR libs with system ones. GMP is not really well maintained, so there could be difficulties to download sources to build it(conan is doing this). And MPFR is depends on GMP, so we need to replace it also
> fix: replace gmp and mpfr libs from conan with libs from system

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/pbft/proposed_blocks.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/proposed_blocks.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/pbft_manager_test.cpp
Do not use rounds for saving proposed blocks. Rason:
This line probably contains logic bug:
`auto block = getValidPbftProposedBlock(period, round - 1, *previous_round_next_voted_value_);`
Theoretical scenario when this would not work:
1. lets say in round 1 we found 2t+1 soft votes for block A, so nodes next voted it
2. we found 2t+1 next votes for block A in round 1, so we moved for round 2
3. In round 2, nobody propose/soft/cert vote(for whatever reason) but everyone next votes block A in first finish step because it is 2t+1 next voted value from previous round(1) - here getValidPbftProposedBlock(period, round - 1, *previous_round_next_voted_value_)should still work as it was saved in round 1 in proposed blocks
4. In round 3 the scenarionas in round 2 is repeated. Nobody …
> fix: do not saved proposed blocks based on rounds, use just periods

- libraries/common/include/common/constants.hpp
- libraries/core_libs/consensus/include/dag/dag_block_proposer.hpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/dag_block_packet_handler.cpp
- tests/dag_block_test.cpp
Added limit of max 16 tips in a DAG block to block malicious producers creating dag blocks with unlimited number of tips.
If there is more then max possible tips to be included in a block, prioritizing tips with higher level and unique producer. This serves as protection from malicious producers producing too many blocks at the same level. This is in combination with the CPU cost of such an attack should probably be enough to discourage it but slashing could be later introduced as well.
Added check that the same tip/pivot is not included more than once within the same dag block.
Main idea in limiting the number of tips is to prevent someone maliciously pointing to large number of old blocks or someone producing too many blocks on the same level. This change in combination with the VDF …
> chore: dag tips verification

- libraries/core_libs/network/rpc/eth/Eth.cpp
Remove miner filed from block returned in RPC methods
> fix: remove miner from block returned in RPC methods

- libraries/core_libs/consensus/include/final_chain/final_chain.hpp
- libraries/core_libs/consensus/include/final_chain/state_api.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/final_chain/state_api.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- tests/full_node_test.cpp
Review this PR as well:
https://github.com/Taraxa-project/taraxa-evm/pull/136
For a light node deleting the data from the state_db. This is done with method prune which instructs to delete all the data which is  below light_node_history number of blocks
> chore: prune light node

- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
There was a TODO for implementing protection against ddos attack through generating reward votes with potentially unlimited rounds... 
There is a dummy protection, wich I think is sufficient enough - if we pushed the block lets say at period 10 & round 1, we expect all other nodes to push the same block max at period 10 & round 101 - there is a 100 rounds buffer
> chore: remove todo for already implemented feature

- doc/RPC.md
- libraries/cli/include/cli/config_jsons/default/default_genesis.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/types/dag_block/include/dag/dag_block.hpp
- libraries/types/dag_block/src/dag_block.cpp
- libraries/vdf/include/vdf/config.hpp
- libraries/vdf/include/vdf/sortition.hpp
- libraries/vdf/src/config.cpp
- libraries/vdf/src/sortition.cpp
- tests/crypto_test.cpp
- tests/dag_block_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/pbft_chain_test.cpp
- tests/test_util/src/node_dag_creation_fixture.cpp
This PR changes the DAG proposal to be dependent on the stake that a node has. This is accomplished by occasional decreasing difficulty for nodes with higher stake. All nodes will still have a probability of producing DAG blocks but nodes with higher stake will produce more blocks relative to its stake.
> chore: dag production dependent on stake

- libraries/core_libs/consensus/include/dag/dag_block_proposer.hpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/node/src/node.cpp
- tests/dag_block_test.cpp
- tests/dag_test.cpp
A limitation is added that a DAG block together with its tips is not allowed to have a gas limit over the pbft gas limit. This will make overweight pbft blocks very unlikely to happen. There are some edge cases when block could have pivot of one level and multiple levels of tips which could make overweight pbft blocks but this should be extremely rare.
> chore: gas limit on dag block tips

- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
I added bunch of log messages, but the actual fix is 1 liner: 
`const auto tmp_reward_votes = getRewardVotes(round_it, reward_votes_hashes, reward_votes_block_hash_, copy_votes);`
inestad of:
`const auto tmp_reward_votes = getRewardVotes(found_round_it, reward_votes_hashes, reward_votes_block_hash_, copy_votes);
`
> fix: use correct round when checking reward votes

- tests/CMakeLists.txt
- tests/rpc_test.cpp
Fix incorrect binary in ctest for `rpc_test`. So we didn't executed this at all during ctest runs
> fix: incorrect binary for rpc_test in ctest

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_next_votes_sync_packet_handler.cpp
- tests/vote_test.cpp
On testnet these error logs often appear:
Taraxa_N1_02242023_053224_00045.log:0x00007ff33affd640 18551e35… GET_NEXT_VOTES_SYNC_PH [2023-02-24 06:49:07.223596] ERROR: No next votes returned for period 76723, round 1
Taraxa_N1_02242023_053224_00045.log:0x00007ff342ffd640 18551e35… GET_NEXT_VOTES_SYNC_PH [2023-02-24 06:49:07.393348] ERROR: No next votes returned for period 76723, round 1
This can happen when vote sync is done for votes which might have just been gossiped. Now we log an error only if votes are missing but if they are already known to peer only a debug log is written.
The change in vote_test was done because this check was never correct to begin with and test could fail. If node 0 is sending vote to nodes 1 and 2, there is no guarantee that the node 0 will not get this vote in …
> chore: vote sync error log remove

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/vote_manager/verified_votes.hpp
- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- tests/pbft_manager_test.cpp
- tests/vote_test.cpp
New mechanism for lambda exponential backoff:
- it should fix the issue when we have to wait very long time until new nodes catch up with the rest of the network 
- network gets stalled when we dont have 2t+1 voting power in next voting steps so I keep track of the network_t_plus_one_step for which there is at least t+1 voting power in the network and I consider this step as reference step, which network is at
- if node's current step is more than kMaxSteps(13) behind network_t_plus_one_step, it's lambda stays at initial value
- once the node is less than kMaxSteps(13) behind network_t_plus_one_step, it starts exponentially backing off it's lambda
- this should make sure all nodes eventually catch up with the rest of the network in relatively small amount of time - the outdated nodes keep …
> Issue 2318/fix exponential backoff

- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/get_pbft_sync_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
The goal of this optimization was to avoid saving cert votes twice in the db, once as a cert vote when cert voting a block and second time when treating the same votes as reward votes.
- 2t+1 cert votes are no longer saved once node receives 2t+1 votes but only a short time later when we actually push a pbft block to the chain. They are saved in a db batch as part of an atomic db operation when moving to the next period.
- Additional reward votes that come after pushing the pbft block into chain is saved in reward_votes column
- Total reward votes will consists of votes bundle saved as 2t+1 cert votes and additional reward votes saved individually
> chore: optimize rewards votes handling

- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
Turn off round check for reward votes since it is normal that reward votes are from old round
> Reward votes round check

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- tests/network_test.cpp
Reward votes broadcast/rebroadcast inverval is now based on time spent in a period and not round since advancing rounds is not dependant on reward votes that might be missing.
> chore: rebroadcast votes based on period not round

- conanfile.py
In new version of cpp check there is no `with_z3` build option and we don't need any specific options for macos arm build
> fix: build on arm macs that was broken after update of cppcheck

- CMakeModules/cppcheck.cmake
- libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp
Fix cpp check errors that I saw on latest develop build
> fix: cpp-check warnings on build

- libraries/common/include/common/encoding_rlp.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp
InvalidEncodingSize was inherited from std::invalid_argument exception, so we was incorrectly processing this RLP related exception(we wasn't marking sender node as malicious).
> fix: RLP InvalidEncodingSize inherits from RLPException

- charts/taraxa-node/CHANGELOG.md
- charts/taraxa-node/Chart.yaml
- charts/taraxa-node/templates/bootnode.yaml
- charts/taraxa-node/templates/consensus-node.yaml
- charts/taraxa-node/templates/taraxa-node.yaml
- charts/taraxa-node/values.yaml
We want to be able to opt-in for chaos. Used [chaos-monkey](https://github.com/asobti/kube-monkey)
Opt-ins for chaos by adding labels to `StatefulSet`s.
Added labels to pod templates (and metamata of `StatefullSep` app as well) in `StatefulSet` of boot, rpc and consensus nodes.
> [helm-chart]: labels for kube-monkey

- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
Make gas limits smaller. For dag it will be equal to 31.5M which is equal to 1500 basic transfer transactions. And 315M for pbft block, but this is not a hard cap and actual pbft block could be larger in some situations
> fix: make gas limits smaller for all of our networks

- doc/building.md
1. I was not able to build conan libraries without specifying:
`conan profile update settings.compiler.compiler.cppstd=14`
in clang conan profile
2. Seems like there is already clang14 in brew ?
> chore: adjust mac building compilation

- tests/final_chain_test.cpp
- tests/rpc_test.cpp
- tests/test_util/include/test_util/test_util.hpp
Add revert reason to execution error in result of dry_run_transaction. This is how it work in geth and will make debugging on contracts much easier
> fix: add revert reason to execution error

- libraries/core_libs/network/rpc/eth/Eth.cpp
- tests/final_chain_test.cpp
- tests/rpc_test.cpp
Fix for transactions estimation. Before this fix some transactions with internal calls to other contracts(and maybe in some other cases) was running out of gas. So estimations wasn't correct
> fix: gas estimations for transactions with internal calls

- libraries/cli/include/cli/config.hpp
- libraries/cli/src/config.cpp
- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
Pruning state_db in a light node requires deleting very large number of db entries in the state_db which can take a long time. Running this synchronously while running a node makes this even slower and node is unable to progress while doing this. Running it asynchronously also slows done the node and causes some crashes that are still being investigated. It is questionable it is feasible and practical to do this while node is running.
This probably would not be a problem is state_db is not growing at the rate it is now.
This change will make state_db prune run only manually on cmd line argument prune-state-db.
Deleting old period_data is fast so this still works in a light node same as before with data being deleted while running the node.
> chore: prune state_db manually

- CMakeLists.txt
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/migration/migration_base.hpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/migration/migration_manager.cpp
- libraries/core_libs/storage/src/storage.cpp
Change the way we are processing db versions change. 
So after this change we are applying migrations on minor version change and rebuilding db on major version change
> feat: change how we process db versions changes

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
Check state root is valid on processing synced pbft blocks
> chore: check state root on syncing

- libraries/core_libs/consensus/include/final_chain/state_api.hpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/final_chain/state_api.cpp
- tests/full_node_test.cpp
Review this as well:
https://github.com/Taraxa-project/taraxa-evm/pull/165
Main and account node databases are huge with large number of entries. Any prune where deleting these entries one by one is taking a very long time. This is avoided by having prune load the data in memory that is to be kept and than deleting the entire column in the database at once and recreating it and populating it with data stored in memory. This makes the prune run in about 3 minutes for a month of data.
Since the prune is relatively fast it can be started manually but it is also run on restart for a light node.
> chore: improve prune

- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- libraries/config/CMakeLists.txt
- libraries/config/include/config/hardfork.hpp
- libraries/config/include/config/state_config.hpp
- libraries/config/src/hardfork.cpp
- libraries/config/src/state_config.cpp
- libraries/core_libs/consensus/include/rewards/block_stats.hpp
- libraries/core_libs/consensus/include/rewards/rewards_stats.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/rewards/rewards_stats.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/CMakeLists.txt
- tests/rewards_stats_test.cpp
- tests/test_util/include/test_util/test_util.hpp
- tests/test_util/src/test_util.cpp
Add option to specify different rewards distribution frequency as a hardfork. Default distribution frequency is every block, so until we will add some record to hardforks this version is still should be compatible with latest release.
So to change rewards distribution frequency we need to add a new element to `rewards_distribution_frequency` in `hardforks`.
For example map with {{101, 20}, {201, 10}} elements means:
1. for blocks [1,100] we are distributing rewards every block
2. for blocks [101, 200] rewards are distributed every 20 block. On blocks 120, 140, etc.
3. for blocks after 201 rewards are distributed every 10 block. On blocks 210, 220, etc.
> feat: add option to change rewards distribution frequency with hardfork

- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- libraries/common/include/common/range_view.hpp
- libraries/config/CMakeLists.txt
- libraries/config/include/config/hardfork.hpp
- libraries/config/include/config/state_config.hpp
- libraries/config/src/hardfork.cpp
- libraries/config/src/state_config.cpp
- libraries/core_libs/CMakeLists.txt
- libraries/core_libs/consensus/include/final_chain/contract_interface.hpp
- libraries/core_libs/consensus/include/final_chain/rewards_stats.hpp
- libraries/core_libs/consensus/include/final_chain/state_api.hpp
- libraries/core_libs/consensus/include/rewards/block_stats.hpp
- libraries/core_libs/consensus/include/rewards/rewards_stats.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/final_chain/rewards_stats.cpp
- libraries/core_libs/consensus/src/final_chain/state_api.cpp
- libraries/core_libs/consensus/src/rewards/block_stats.cpp
- libraries/core_libs/consensus/src/rewards/rewards_stats.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- libraries/types/pbft_block/include/pbft/pbft_block.hpp
- tests/CMakeLists.txt
- tests/final_chain_test.cpp
- tests/rewards_stats_test.cpp
- tests/state_api_test.cpp
- tests/test_util/include/test_util/test_util.hpp
- tests/test_util/src/test_util.cpp
Refactors rewards stats processing, so we can process rewards in a batches every N blocks
https://github.com/Taraxa-project/taraxa-evm/pull/162
> refactor: rewards stats passing

- libraries/common/include/common/types.hpp
- libraries/core_libs/network/rpc/eth/Eth.cpp
- libraries/core_libs/network/rpc/eth/LogFilter.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- tests/final_chain_test.cpp
Fix blooms generated by bloomPossibilities method. Because of this eth_getLogs rpc method was returning not all events as two elements in array was meaning AND, but not OR as it should be
> fix: bloomPossibilities topics processing

- doc/RPC.md
- libraries/core_libs/network/rpc/Taraxa.cpp
- libraries/core_libs/network/rpc/Taraxa.h
- libraries/core_libs/network/rpc/Taraxa.jsonrpc.json
- libraries/core_libs/network/rpc/TaraxaClient.h
- libraries/core_libs/network/rpc/TaraxaFace.h
- libraries/core_libs/network/rpc/eth/Eth.cpp
- libraries/core_libs/network/rpc/eth/Eth.h
- libraries/core_libs/network/rpc/eth/data.hpp
Add RPC methods to speed up indexing. Also data is processed concurrently in this methods as we have some additional requests to the db and getting sender from signature
1. `taraxa_getPeriodTransactionsWithReceipts` to get all transactions with receipt data for specified period. 
2. `taraxa_getPeriodDagBlocks` to get all dag blocks for specified period
> feat: add RPC methods to speed up indexing

- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/v1/get_pbft_sync_packet_handler.cpp
This is a fix for the NetworkTest.sync_large_pbft_block where the sync would fail for a node where there is only a block with period 1 in the chain
> chore:fix sync large pbft block test

- libraries/common/include/common/util.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/tarcap/taraxa_peer.cpp
- tests/network_test.cpp
Cache that previously each TaraxaPeer uses for keeping known transactions, votes and blocks hashes get always fully populated to maximum size. With some nodes configured to have up to 50 connected peers this cache can take significant memory usage.
The change is made that the cache entries expire once they are included in block finalizes 10 periods ago. This makes the cache small when ever network is progressing normally and it will only reach maximum size in case network gets stuck and there is some build up of transactions, dag blocks and votes at the same period.
> chore: optimize peer cache memory usage

- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/full_node_test.cpp
- Clear light node history on startup
- dag_blocks_level column created based on dag_blocks_index which is removed to have column ordered by level to support deleting by level for light node
- Fix issue with incorrect transaction hash used to delete old transactions on light node
- Delete additional columns data for light node: old transactions data in trx_period and old dag blocks in dag_block_period and dag_block_level
> chore: light node optimizations and fix

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
In case execution was delayed, state root validation would fail in processing synced pbft block which would cause marking the node as malicious when processing the next block in the queue.
This is fixed to separately handle two cases:
- when execution is delayed and state root is missing keep waiting in a loop until state root is present
- when state root is invalid clear the entire queue and mark node as malicious
> fix: state root validation on syncing

- libraries/aleth/libp2p/NodeTable.cpp
With the current approach a node that never responds stays in the nodetable if it is being pinged constantly to different endpoints.  With this change such node will be removed after the ping timeout to make room for other nodes. Once a node responds with a pong all other pings to other endpoints are removed.
> chore: improve ping timeout handling on discovery

- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
Even with some latest optimizations getting transactions from period data to be able to delete old data from Columns::final_chain_receipt_by_trx_hash can sometimes take up to 20 seconds. With DagManager::clearLightNodeHistory running synchronously blocking the node from pushing new blocks to the chain this causes node to get out of synced state.
Change is made that clearing light node history is now done on a separate thread. Since this is done once an hour, a new thread is always created since there is no need to have an active thread in thread pool which is only utilized once an hour for a light node.
> chore: async clear light node history

- libraries/core_libs/network/src/tarcap/packets_handlers/latest/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/shared_states/pbft_syncing_state.cpp
If a node gets out of sync (this is known to happen while deleting old period_data blocks in a light node which blocks us from pbft progressing) and pbft syncing is restarted, a malicious peer exception can happen once pbft blocks are synced but dag blocks are not. Allow dag re-syncing once pbft syncing completes.
> chore: allow dag resyncing after node is out of pbft sync

- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
Since clearing light node data while running the node resulted in node getting out of sync, this is now only done on restarting the node.
> chore: light node clearing on restart only

- libraries/aleth/libp2p/NodeTable.cpp
Scenario easily reproducible on the devnet:
- node is discovered with correct endpoint(IP/port) A. It is pinged and successfully added to the NodeTable with endpoint A.
- same node is discovered again with incorrect endpoint IP/port B. Node is pinged to this incorrect endpoint B and no pong response is received
-  In doHandletimeout node is removed from the NodeTable even though node contains correct endpoint A
This fix only removes the node from the NodeTable if it was actually pinged to the same address which is in the NodeTable.
Example log of this case:
0x00007f5feffff640  discov [2023-08-24 13:20:45.536576] : Not dropping node ##1755f430… on ping timeout for 34.134.242.50:4731  as previous endpoint still valid 34.134.242.50:32002
> chore: improve discovery ping handling

- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- Delete data from trx_period, pbft_block_period and final_chain_log_blooms_index columns older than light node history
- dag_block_period column was not correctly deleted, fixed
With these changes size of the db snapshot columns with 7 days history:
period_data 3.2GB
final_chain_receipt_by_trx_hash 413MB
trx_period 371MB
All other columns smaller than 100MB
> chore: light node size optimization

- libraries/core_libs/consensus/include/dag/dag_block_proposer.hpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/node/src/node.cpp
- tests/crypto_test.cpp
- tests/dag_test.cpp
- tests/full_node_test.cpp
- tests/state_api_test.cpp
Probability to create a DAG block for a eligible proposer was determined by node vote_count/total_vote_count expressed in 1/1000 units and used in DAG difficulty threshold calculation.
On current mainnet total vote count is 2M votes and minimal validator vote is 50 votes. With 1/1000 of 2M being 200 votes, current algorithm gives validators which are at minimum 50 votes much higher yield that any validator above that.
To fix this the base value for these calculation post magnolia hardfork is changed from total_vote_count to a maximum vote count per validator. For the current mainnet this means a change from 2M to 80k. With the base value being 80k, 1/1000 of 80k is only 8 votes which is significantly smaller than the current minimal delegation for a validator.
At the time of the hardfork …
> chore: improve dag propose probability

- libraries/cli/include/cli/config_jsons/default/default_config.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
If we do compounding a user that accidentally started two nodes might get jailed for a very long time if it keeps double voting. I think it should be enough to just keep setting the jail time from current block without compunding.
Jailing is not enabled without report_malicious_behaviour set to true so adding for all networks.
For testnet and devnet reduced jail_time to 1000 which is about an hour to make testing it easier.
> chore: jail updates

- libraries/cli/include/cli/config_jsons/default/default_config.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_config.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_config.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/pbft_sync_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/pbft_sync_packet_handler.cpp
While node is syncing gossiping messages like transactions/dag blocks/votes packets are ignored up to the point of deep_syncing_threshold of being synced. This threshold was set to only 10 blocks. Since 10 blocks are usually very quickly processed we would usually lose the recent votes which would create two problems:
1. Missing reward votes for the cert voted block making us unable to push the cert voted block requiring us to restart the syncing
2. Not processing votes also did not gave us most up to date info about peer pbft chain sizes delaying the actual syncing up to the latest block
Sometimes this behavior can cause long time of nodes restarting syncing and not being able to fully join the consensus.
Fix is done by increasing the deep_syncing_threshold to 50 and threshold using the …
> fix: pbft syncing gossip transition

- libraries/common/include/common/vrf_wrapper.hpp
- libraries/common/src/vrf_wrapper.cpp
- libraries/core_libs/consensus/include/final_chain/final_chain.hpp
- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/vote_manager/vote_manager.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pbft/period_data_queue.cpp
- libraries/core_libs/consensus/src/vote_manager/vote_manager.cpp
- libraries/core_libs/network/include/network/ws_server.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/v1/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/ws_server.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/types/vote/include/vote/vote.hpp
- libraries/types/vote/include/vote/vrf_sortition.hpp
- tests/full_node_test.cpp
Rocksdb options sync which was set to false only in final_chain db operations makes every write very slow because it waits for the data to be written to disk. This is specially noticeable on slower SSD and HDD. Removing it improves syncing speed. I do not see any reason why we ever used this.
When syncing faster than processing the blocks we sync which can happen often, a condition variable is used to notify the waiting blocks once a new block is finalized. This also reduces waiting time and improves syncing speed.
> chore: improve syncing speed

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/transaction_test.cpp
When saving transactions from dag block just added to the DAG there were some unneeded db lookups which were a performance bottleneck. On verifying the DAG block it is ensured that all transactions that are not finalized and not yet part of the DAG are within the transaction pool so there is no need to do additional db lookups.
The PR also includes a fix for the issue in rebuild db which was causing db_rebuild test to intermittently fail.
> chore: optimize dag block save

- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
non_proposable_transactions_ were not being properly cleaned once such a transaction was included in DAG block which caused incorrect transactions handling.
> fix: transaction pool

- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
gas_limit for DAG and Pbft blocks was reduced as part of this PR: https://github.com/Taraxa-project/taraxa-node/pull/2424
The gas limit basically limits how many transactions we can execute per second together with the other parameters. With the current settings we produce just a little over 1 dag block per second. With aiming for dag block efficiency of 50% only half of transactions in dag blocks are unique transactions. This means that the gas limit in practice allows us to put max of 1500 transactions in dag block and is basically limiting us to not have over 750 transactions per second.
Increased the limit to support 5000 transactions in DAG block and 50000 in PBFT block on devnet to be able to perform high TPS testing.
Reverting transactions check that was removed as part of syncing …
> chore: increase gas limit on devnet

- .clang-format
- .dockerignore
- libraries/core_libs/network/rpc/EthFace.h
`!.clang-format` added to `.dockerignore`, so `COPY` command in the Dockerfile will actually copy this config and formatting will be checked properly
> Fix clang format check and formatting 

- CMakeLists.txt
- Dockerfile
- libraries/cli/include/cli/config_jsons/default/default_genesis.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- libraries/config/include/config/hardfork.hpp
- libraries/config/src/hardfork.cpp
- tests/rewards_stats_test.cpp
> chore: fix commision rewards

- libraries/core_libs/consensus/include/rewards/rewards_stats.hpp
- libraries/core_libs/consensus/src/rewards/rewards_stats.cpp
Another solution would be to have both:
```
std::unordered_map<PbftPeriod, BlockStats> unordered_blocks_stats_;
std::map<PbftPeriod, BlockStats> ordered_blocks_stats_;
```
inside Stats class.
I would still need to use at least 1 lambda function + aspen hf would have to be checked inside multiple functions...
I prioritized this solution as it is simpler and to do extra sort on 100 items every 100th block does not affect performance...
> order blocks stats after aspen hardfork rt one

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/include/pillar_chain/pillar_block.hpp
- libraries/core_libs/consensus/include/pillar_chain/pillar_chain_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/pillar_chain/pillar_block.cpp
- libraries/core_libs/consensus/src/pillar_chain/pillar_chain_manager.cpp
- libraries/core_libs/consensus/src/pillar_chain/pillar_votes.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/common/ext_votes_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pillar_chain_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/pillar_chain_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/votes_bundle_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/storage/src/storage.cpp
- libraries/types/pbft_block/include/pbft/period_data.hpp
- libraries/types/pbft_block/src/period_data.cpp
- libraries/types/vote/include/vote/pillar_vote.hpp
- libraries/types/vote/include/vote/votes_bundle_rlp.hpp
- libraries/types/vote/src/pillar_vote.cpp
- libraries/types/vote/src/votes_bundle_rlp.cpp
- tests/full_node_test.cpp
- tests/test_util/src/test_util.cpp
> Issue 2693/pillar votes syncing

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/node/src/node.cpp
- libraries/types/pbft_block/CMakeLists.txt
- libraries/types/pbft_block/include/pbft/pbft_block.hpp
- libraries/types/pbft_block/include/pbft/pbft_block_extra_data.hpp
- libraries/types/pbft_block/src/pbft_block.cpp
- libraries/types/pbft_block/src/pbft_block_extra_data.cpp
- tests/final_chain_test.cpp
- tests/pbft_chain_test.cpp
Pbft block after aspen hf part two contains an optional extra field similar to extra_data field in ethereum block. Final chain ethereum block representation contains the field. After aspen hf, this field will contain a version info in format:
{'T', TARAXA_MAJOR_VERSION, TARAXA_MINOR_VERSION, TARAXA_PATCH_VERSION, TARAXA_NET_VERSION})
> chore: adding version to pbft block

- libraries/core_libs/consensus/src/dag/dag_manager.cpp
Tip not present error log is showing up on all of our networks and it was actually logged even if we had a tip. Fixed by logging this only if the tip is missing.
> chore: remove incorrect missing tip log

- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
There is a race condition which can cause an exception on processing packets and other places. Final chain commit is performed before the EVM state commit. In between these two calls this can happen:
1. Caller call getBlock from cache with block_num higher than the last block number, this updates the last block number to be over what is executed in EVM
2. Another thread asks for account from EVM using the last block which is not yet present in the EVM
This causes this exception for instance in processing of transaction packet:
0x00007cc72d7fa640 V2_TRANSACTION_PH [2024-03-21 15:22:17.365802] ERROR: Exception caught during packet processing: Requested blk num:941, last committed:940 .PacketData: {"from_node_id":"53b7010037543c15159d6dc77c7ea8e60c61489a06ebf1a7b0a940332c1ef73d9774e4323da34c3 …
> chore: final chain state

- CMakeLists.txt
- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/common/include/common/constants.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/transaction_packet_handler.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_peer.hpp
- libraries/core_libs/network/src/network.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/network/src/tarcap/taraxa_peer.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/transaction_test.cpp
In a single transaction send interval which is 100ms only one packet of max of 500 transactions is sent to another peer.
Different connected peers will be sent different packet of 500 transactions grouped by account so that transactions are gossiped more evenly around the network.
Each packet will also contain up to additional 5000 transactions hashes to notify the other peers of the transactions in transaction pool to avoid receiving same transactions back and forth between nodes.
These changes significantly reduces the network data by reducing the number of times same transaction is shared between nodes which improves performance. This also increases dag efficiency by spreading transactions out more evenly around the network.
This change only applies if we have high transactions load. …
> chore: trxs gossip improvements

- libraries/common/include/common/constants.hpp
- libraries/config/src/network.cpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/dag_block_packet_handler.hpp
- libraries/core_libs/network/include/network/threadpool/packets_blocking_mask.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/dag_block_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/dag_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/transaction_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
- libraries/core_libs/network/src/threadpool/packets_blocking_mask.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/dag_block_test.cpp
- tests/full_node_test.cpp
- tests/network_test.cpp
- tests/transaction_test.cpp
Various improvements in processing:
Verification of DAG blocks was retrieving all the transactions from pool/caches/db and than the same transactions were retrieved again when adding the block to the DAG and changing transactions statuses. Now transactions retrieved from the verification are returned from DagManager::VerifyBlock and used in adding the DAG block which speeds up DAG block/transactions processing.
Any transactions received in the dag block and dag sync packet is processed directly in adding the dag block packet without previously being saved in transactions pool. This makes processing dag blocks with transactions faster.
DagBlockPacket is modified to include any transactions not already sent to the peer.
Recently finalized transaction is enforced to always contain all the …
> chore: transactions and dag blocks processing improvements

- libraries/config/src/hardfork.cpp
if ficus hf block_num is -1 which is actually uint64_max, adding pillar_blocks_interval to it makes it overflow and isPillarBlockPeriod returns incorrectly true.
> fix: pillar check

- CMakeLists.txt
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- new pillar chain implementation
- node version 1.10.0
- changed boot nodes dns to 0,1,2
- timestamo changed to Tuesday, Jul 23, 2024 10:00:00.000 AM
> increase minor version + genesis

- libraries/core_libs/network/rpc/Taraxa.cpp
- libraries/core_libs/network/rpc/Taraxa.h
- libraries/core_libs/network/rpc/Taraxa.jsonrpc.json
- libraries/core_libs/network/rpc/TaraxaClient.h
- libraries/core_libs/network/rpc/TaraxaFace.h
- libraries/core_libs/node/src/node.cpp
RPC getNodeVersions will retrieve version for any node that produced a pbft block within last 6000 blocks(6 hours) and provide a summary of how many nodes are running each individual version.
> chore: add rpc for retrieving nodes versions

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- tests/full_node_test.cpp
- tests/test_util/include/test_util/samples.hpp
- tests/test_util/include/test_util/test_util.hpp
- tests/test_util/src/samples.cpp
Transactions with no account were not handled correctly. They could end up both in proposable and unproposable transactions since undefined balance ZeroAccount was used for it. Fixed by correclt handling it with transaction never placed in proposable transaction pool
> chore: handle transactions with no account

- libraries/config/include/config/network.hpp
- libraries/core_libs/network/include/network/tarcap/taraxa_capability.hpp
- libraries/core_libs/network/src/tarcap/taraxa_capability.cpp
Improved algorithm for disconnecting nodes on packets queue limit reached:
- Only disconnect if limit is reached for certain time amount and not if there is only a short term burst in queue size
- Disconnect nodes in intervals not to disconnect too many nodes at once
- Drop any new connections if queue is over the limit
These changes improve that we do not disconnect when there is no need to disconnect, not disconnect too many nodes, not allow new connections to keep filling up the queue
> chore: queue limit improvements

- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/vote_packet_handler.cpp
Since different version capabilities have different handlers sending votes from within a single handler resulted in sending votes only to nodes with the same version. 
Gossiping votes with pbft manager gossip vote ensures that the vote is sent to all node versions.
> fix: gossip votes to all capability version

- for_devs/local-net
- libraries/cli/include/cli/config_jsons/default/default_genesis.json
- libraries/config/include/config/hardfork.hpp
- libraries/core_libs/consensus/include/final_chain/data.hpp
- libraries/core_libs/consensus/include/final_chain/final_chain.hpp
- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/storage/include/storage/migration/period_dag_blocks.hpp
- libraries/core_libs/storage/src/migration/dag_block_period_migration.cpp
- libraries/core_libs/storage/src/migration/migration_manager.cpp
- libraries/core_libs/storage/src/migration/period_dag_blocks.cpp
- libraries/types/pbft_block/include/pbft/pbft_block.hpp
- libraries/types/pbft_block/src/pbft_block.cpp
- tests/pbft_manager_test.cpp
Replace `state_root_hash` with `final_chain block hash` in the cornus hf to improve state tracking in pbft blocks
> Change final chain hash

- libraries/types/dag_block/src/dag_block_bundle_rlp.cpp
Using uint16 as transaction index was unsafe for high transactions load where one pbft block could contain over 65k transactions.
> fix: dag block bundle

- libraries/config/include/config/network.hpp
- libraries/config/src/network.cpp
- libraries/core_libs/network/include/network/http_server.hpp
- libraries/core_libs/network/include/network/ws_server.hpp
- libraries/core_libs/network/src/http_server.cpp
- libraries/core_libs/network/src/ws_server.cpp
- libraries/core_libs/node/include/node/node.hpp
- libraries/core_libs/node/src/node.cpp
Limit number of rpc requests that can run on parallel and reject any new connection/requests if over the limit
> chore: rpc requests limit

- libraries/core_libs/network/include/network/tarcap/packets/latest/pillar_votes_bundle_packet.hpp
- libraries/core_libs/network/include/network/tarcap/packets/latest/votes_bundle_packet.hpp
> use optimized rlp format for votes bundles

- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
When creating snapshot and possibly in some other condition it is possible that pbft block was pushed to the chain but pillar block has not been saved when node is stopped. Handle this on restarting the node by calling processPillarBlock if needed
> fix: pillar block save

- libraries/core_libs/consensus/src/dag/sortition_params_manager.cpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/network/include/network/tarcap/packets/latest/pbft_sync_packet.hpp
- libraries/core_libs/network/include/network/tarcap/packets/latest/pillar_votes_bundle_packet.hpp
- libraries/core_libs/network/include/network/tarcap/packets/latest/votes_bundle_packet.hpp
- libraries/core_libs/network/include/network/tarcap/packets_handlers/latest/common/ext_votes_packet_handler.hpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/get_pillar_votes_bundle_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/pbft_sync_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/pillar_votes_bundle_packet_handler.cpp
- libraries/core_libs/network/src/tarcap/packets_handlers/latest/votes_bundle_packet_handler.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- libraries/types/vote/include/vote/votes_bundle_rlp.hpp
- libraries/types/vote/src/votes_bundle_rlp.cpp
- tests/pbft_manager_test.cpp
> refactor periodData getter + fix votes_bundle processing

- libraries/common/include/common/constants.hpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
To avoid proposing too many dag blocks when network is not progressing or slow to progress:
- only propose a block with same or smaller difficulty than the min difficulty of non finalized dag blocks
- limit max number of non finalized dag blocks to 100
> dag proposal improvements

- libraries/aleth/libp2p/Host.cpp
- libraries/aleth/libp2p/Network.h
- libraries/cli/include/cli/config_jsons/testnet/testnet_config.json
- libraries/config/include/config/network.hpp
- libraries/config/src/network.cpp
- libraries/core_libs/network/src/network.cpp
Add trusted nodes configuration option which will prioritize trusted nodes connection and always accept a connection to a trusted node even if over the max connection limit.
> chore: trusted nodes

- libraries/cli/include/cli/config_jsons/default/default_genesis.json
- libraries/cli/include/cli/config_jsons/devnet/devnet_genesis.json
- libraries/cli/include/cli/config_jsons/mainnet/mainnet_genesis.json
- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
- libraries/config/include/config/config.hpp
- libraries/config/include/config/genesis.hpp
- libraries/config/include/config/hardfork.hpp
- libraries/config/src/config.cpp
- libraries/config/src/genesis.cpp
- libraries/config/src/hardfork.cpp
- libraries/core_libs/consensus/include/dag/dag_manager.hpp
- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/consensus/src/final_chain/final_chain.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- tests/dag_block_test.cpp
- tests/pbft_manager_test.cpp
- tests/rewards_stats_test.cpp
- tests/rpc_test.cpp
Increasing gas limit on cornus HF on mainnet
Introducing configurable propose gas limits which limits the gas limit of blocks being proposed. This allows increasing the actual dag blocks limit/size without a need for a consensus change/HF
https://github.com/Taraxa-project/taraxa-evm/pull/258
> chore: propose gas limit

- libraries/config/include/config/config_utils.hpp
- libraries/config/src/config.cpp
- libraries/config/src/config_utils.cpp
- libraries/config/src/network.cpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- Allow setting propose gas limits in config file as hex by modifying getConfigDataAsUInt to accept hex strings
- Remove validation of propose gas limits from FullNodeConfig::validate since the validation depends if over the cornus HF. Add validation in DagBlockProposer constructor by reducing the value to the maximum gas limit allowed
> fix: propose gas limit validation

- libraries/cli/include/cli/config_jsons/testnet/testnet_genesis.json
Increase initial testnet VRF threshold to increase DAG production on starting the network
> Increase initial testnet VRF threshold

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
Due to dag reordering it is possible to include a transaction with no balance in a pbft block. Evm does not increase account nonce for such a transactions. Because of that and relying on nonce to detect duplciate transactions it is possible to include same transaction in two different block.
The fix is to check the entire transactions history.
> fix: no balance duplicate transaction

- libraries/core_libs/network/rpc/jsonrpc_ws_server.cpp
Revert a change where node is throwing an error on an unknown subscription to avoid node crashing. Should be handled differently(probably handleSubscription should be inside of handleRequest)
> fix: dont throw on unsupported or invalid subscription

- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
Use nonce to check if transaction is not executed which is significantly faster than checking full transaction history
> chore: transaction handling optimization

- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/dag/dag_manager.cpp
- libraries/core_libs/storage/include/storage/storage.hpp
- libraries/core_libs/storage/src/storage.cpp
- tests/full_node_test.cpp
When clearing history for any table that has a hash for the key do not delete entry one by one but select values to keep for last 1000 blocks and delete all rest by recreating column.
> chore: pruning optimization

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
recently_finalized_transactions_ were not cleared properly which made them grow without limit and increased memory
> fix: recently finalized transactions memory

- doc/RPC.md
- libraries/core_libs/network/include/network/subscriptions.hpp
- libraries/core_libs/network/rpc/jsonrpc_ws_server.cpp
- libraries/core_libs/network/src/subscriptions.cpp
> fix: always return full data for newHeads subscription

- libraries/common/include/common/thread_pool.hpp
- libraries/common/src/thread_pool.cpp
- libraries/core_libs/consensus/include/pbft/pbft_manager.hpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
On syncing get transactions sender in parallel. This improves syncing speed since getSender() is a bottleneck
> chore: improve syncing

- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- tests/pbft_manager_test.cpp
Any transaction over the propose dag gas limit should not be proposable in pool.
Include smaller gas limit transactions in packtrxs if large one does not fit.
> chore: large gas limit transactions handling

- libraries/core_libs/consensus/include/dag/dag_block_proposer.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
Sharding is still disabled but some improvements and fixes are made:
- Sharding is done based on the sender and not hash to avoid reordering of trnasactions from same sender
- Every 10 period sharding is shuffled not to have same sender always use the same nodes
> Sharding improvements

- libraries/common/include/common/constants.hpp
- libraries/core_libs/consensus/src/dag/dag_block_proposer.cpp
- libraries/core_libs/consensus/src/pbft/pbft_manager.cpp
If no new dag block pointing to last anchor, use any non finalized dag block with maximum level to avoid creating empty pbft blocks.
Adjust canceling proposing dag block to only give up if a block of higher level is already created. This makes creation of dag block with different difficulties and timing which makes dag creation less bursty.
> chore: improve dag anchor selection

- libraries/app/src/app.cpp
- libraries/config/include/config/config.hpp
- libraries/config/src/config.cpp
- libraries/core_libs/consensus/include/transaction/gas_pricer.hpp
- libraries/core_libs/consensus/include/transaction/transaction_manager.hpp
- libraries/core_libs/consensus/include/transaction/transaction_queue.hpp
- libraries/core_libs/consensus/src/transaction/gas_pricer.cpp
- libraries/core_libs/consensus/src/transaction/transaction_manager.cpp
- libraries/core_libs/consensus/src/transaction/transaction_queue.cpp
- tests/gas_pricer_test.cpp
Gas pricer now supports two configurable modes. 
One is the old mode of getting gas price based on last N blocks.
New default config for getting gas price estimate is to get the gas price that will include the transaction in the next proposed dag block based on the current state of transaction pool.
> chore: improve gas pricer
